package com.favorable.viajes;

import android.app.*; import android.os.*; import android.graphics.Color; import android.graphics.drawable.GradientDrawable;
import android.content.*; import android.view.*; import android.graphics.pdf.PdfDocument; import android.graphics.Paint; import java.io.*; import android.view.inputmethod.InputMethodManager; import android.widget.*;
import java.text.*; import java.util.*;

public class MainActivity extends Activity {
 final int BG=Color.rgb(8,13,10),PANEL=Color.rgb(20,29,23),PANEL2=Color.rgb(29,40,32),GREEN=Color.rgb(122,205,69),WHITE=Color.WHITE,MUTED=Color.rgb(177,190,181),RED=Color.rgb(218,70,70),YELLOW=Color.rgb(239,190,55);
 LinearLayout root,board,detailPanel,daysHeader; TextView weekTitle,foot,detailBody; Button detailOpen,detailState,detailEdit,detailMove; int selectedRow=-1,selectedDay=-1,selectedIdx=-1; int photoRow=-1,photoDay=-1,photoIdx=-1; Calendar week=Calendar.getInstance(); SharedPreferences db;
 String[] days={"LUN","MAR","MIÉ","JUE","VIE","SÁB","DOM"}; String[] dayLong={"LUNES","MARTES","MIÉRCOLES","JUEVES","VIERNES","SÁBADO","DOMINGO"};
 String[] companies={"ACMET","AGUSTIN RIOS","ALBERTO AGUILAR","ALCLA","ANDREANI","ATOMO","ATOMO on line","AVA TUNUYAN","AVA TUPUNGATO","AVA UGARTECHE","BAGGIO","BANCO NACION","BARNIPLAS","BELHARA","BODEGA GUANACACHE","C.V LUJAN","CARTOCOR","CARTOCOR","CENTRO VERDE GLLEN (AGUAR)","CENTRO VERDE GLLEN (GRILLI)","CENTRO VERDE LAS HERAS","COCA COLA","COCA COLA FRIO","COOP. FARM.","COSMOPOLITAN","CUYO PLACAS","DAIANA MARTIN","DAIANA MARTIN","DAIANA MARTIN","DINO CONTE","DOÑA PAULA","DUCIDA","ECO DE LOS ANDES","FLORENA","GP COQUIMBITO","GP N.CORREA","GP SANTA ANA","GREGORIO MAR.","GUSANTI","HAROLDOS","HIERROS MAL","HIMAN","HOLCIM","IPC","KNAUF","LA RURAL","LAS PERDICES","LUCIANO LUCERO","LUIGI BOSCA","LUIS ABREGO","MARIANETI","MASOL","MAYA","MELTO","MIGUEL PEREZ","MINET","MUNICIP LAVALLE","NAV. COR AGRELO","PAOLA VALDEBEN","PATRICIA (WAIKIKI)","RENEZ ALVAREZ","ROQUE VIGO","RUIZ FABIAN","SANDRA MARZAN","SILVANO SPURI","SOLVENCIA","SOSA","TALCA","UNILEVER","VEA CD","VEA UNIMEV","VENTURA","VERALLIA","WEINERT","ZUCCARDI"};
 boolean favoritesOnly=false;
 String[] trailers={"ELEGIR ACOPLADO","SIN ACOPLADO","AE 056 WL · ACOPLADO","CMC 802 · ACOPLADO","TCM 673 · ACOPLADO","TDH 077 · ACOPLADO"};
 String[] materials={"CARTON","VIDRIO","STRECH","TERMOCONTRAIBLE","ALUMINIO","CHATARRA","PET CRISTAL","BIDONES","COLOR"};
 String[] destinations={"RELLENO SANITARIO","HOLCIM","FAVORABLE","OTRO"};
 String[] states={"PEDIDO PENDIENTE","PROGRAMADO","EN CURSO","REALIZADO","REPROGRAMADO","CANCELADO"};
 String[] drivers={"ELEGIR CHOFER","AGUERO EDGARDO JESUS","CATALDO DANIEL HECTOR","CATALDO FRANCO","CATALDO SERGIO JAVIER","FUNES FABIAN ROQUE","GINIOLI MATIAS VICENTE","MELA GERARDO DARIO","OLMOS JUAN CARLOS","SOTELO FRANCO"};
 String[] trucks={"ELEGIR CAMIÓN","AC 592 VP · IVECO EUROCARGO","AG 824 DR · IVECO TECTOR","AD 604 WN · IVECO DAILY","AD 670 RD · IVECO TECTOR","AE 056 WX · IVECO TECTOR","AF 252 GE · IVECO TECTOR","DOJ 270 · M. BENZ LK","GIP 868 · M. BENZ L","ILH 135 · IVECO DAILY","OIN 428 · FORD CARGO","PQJ 269 · IVECO EUROCARGO","DPI439 · M. BENZ LK","AI 375 JY · IVECO TECTOR"};
 public void onCreate(Bundle b){super.onCreate(b);db=getSharedPreferences("viajes",0);loadCompanies();build();}
 void loadCompanies(){String extra=db.getString("custom_companies","");if(extra.trim().length()>0){ArrayList<String> all=new ArrayList<>(Arrays.asList(companies));for(String c:extra.split("\\|\\|")){String n=c.trim();boolean exists=false;for(String q:all)if(q.equalsIgnoreCase(n)){exists=true;break;}if(n.length()>0&&!exists)all.add(n);}companies=all.toArray(new String[0]);}saveCompanies();}
 void saveCompanies(){StringBuilder z=new StringBuilder();for(int i=0;i<companies.length;i++){if(i>0)z.append("|");z.append(companies[i]);}db.edit().putString("catalog_companies",z.toString()).apply();}
 int ensureCompany(String name){name=name.trim().toUpperCase(new Locale("es","AR"));for(int i=0;i<companies.length;i++)if(companies[i].equalsIgnoreCase(name))return i;if(name.length()==0)return 0;String[] n=Arrays.copyOf(companies,companies.length+1);n[n.length-1]=name;companies=n;String ex=db.getString("custom_companies","");boolean inCustom=false;for(String q:ex.split("\\|\\|"))if(q.trim().equalsIgnoreCase(name)){inCustom=true;break;}if(!inCustom)db.edit().putString("custom_companies",ex.length()==0?name:ex+"||"+name).apply();saveCompanies();return n.length-1;}
 protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==700&&res==RESULT_OK&&data!=null&&data.getData()!=null){try{getContentResolver().takePersistableUriPermission(data.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}String k=evidenceKey(photoRow,photoDay,photoIdx);String old=db.getString(k,"");db.edit().putString(k,old.length()==0?data.getData().toString():old+"||"+data.getData()).apply();saveHistory("FOTO",companies[photoRow]+" · "+days[photoDay]);Toast.makeText(this,"Evidencia agregada",Toast.LENGTH_SHORT).show();}}
 TextView tx(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(14,10,14,10);return v;}
 GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(11);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setMinHeight(54);b.setPadding(10,6,10,6);b.setBackground(shape(PANEL2,18));return b;}
 int stateColor(String v){if(v.contains("REALIZADO"))return GREEN;if(v.contains("EN CURSO"))return YELLOW;if(v.contains("CANCELADO"))return RED;if(v.contains("REPROGRAMADO"))return Color.rgb(255,145,60);if(v.contains("PEDIDO PENDIENTE"))return Color.rgb(120,170,220);return WHITE;}
 int widthDpSafe(){return (int)(getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density);}
 int heightDp(){return (int)(getResources().getDisplayMetrics().heightPixels/getResources().getDisplayMetrics().density);}
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 TextView kpi(String title,String value,int color){TextView v=tx(value+"\n"+title,14,WHITE);v.setGravity(Gravity.CENTER);v.setTypeface(null,1);GradientDrawable g=shape(PANEL,dp(14));g.setStroke(dp(1),color);v.setBackground(g);v.setPadding(dp(12),dp(10),dp(12),dp(10));return v;}
 LinearLayout kpiBar;
 void updateKpis(){if(kpiBar==null)return;kpiBar.removeAllViews();int total=0,done=0,pending=0,course=0,repro=0,cancel=0;for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String tv:trips(r,d)){total++;if(tv.contains("REALIZADO"))done++;else if(tv.contains("EN CURSO"))course++;else if(tv.contains("REPROGRAMADO"))repro++;else if(tv.contains("CANCELADO"))cancel++;else pending++;}String[] t={"TOTAL","REALIZADOS","EN CURSO","PENDIENTES","REPROGRAMADOS","CANCELADOS"};int[] n={total,done,course,pending,repro,cancel};int[] c={WHITE,GREEN,YELLOW,Color.rgb(120,170,220),Color.rgb(255,145,60),RED};for(int i=0;i<t.length;i++){TextView v=kpi(t[i],String.valueOf(n[i]),c[i]);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(118),dp(68));lp.setMargins(dp(4),dp(4),dp(4),dp(8));kpiBar.addView(v,lp);}}
 void build(){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(16),dp(10),dp(12),dp(8));top.setBackground(shape(Color.rgb(10,22,14),0));
  TextView brand=tx("♻  FAVORABLE\n     LOGÍSTICA",widthDpSafe()<500?18:22,GREEN);brand.setTypeface(null,1);brand.setSingleLine(false);top.addView(brand,new LinearLayout.LayoutParams(0,dp(64),1));
  Button summaryTop=bt("RESUMEN");summaryTop.setTextSize(8);summaryTop.setTextColor(Color.BLACK);summaryTop.setBackground(shape(YELLOW,dp(10)));summaryTop.setOnClickListener(v->weekMovementSummary());top.addView(summaryTop,new LinearLayout.LayoutParams(dp(widthDpSafe()<500?72:82),dp(34))); TextView claim=tx("LOGÍSTICA QUE TRANSFORMA",widthDpSafe()<500?8:11,YELLOW);claim.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);top.addView(claim);root.addView(top);

  LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.HORIZONTAL);root.addView(shell,new LinearLayout.LayoutParams(-1,0,1));
  int widthDp=(int)(getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density);
  if(widthDp>=900){
   LinearLayout side=new LinearLayout(this);side.setOrientation(LinearLayout.VERTICAL);side.setPadding(dp(8),dp(10),dp(8),dp(8));side.setBackgroundColor(Color.rgb(12,20,15));
   TextView sh=tx("GESTIÓN DE RETIROS",10,MUTED);side.addView(sh);
   String[] sm={"▣  SEMANA","□  DÍA","!  PEDIDOS PENDIENTES","◷  HISTORIAL","▦  EMPRESAS","♟  CHOFERES","▰  CAMIONES","▱  ACOPLADOS","▤  CONTENEDORES","⚙  SERVICIOS","◆  MATERIALES","⌖  DESTINOS","▥  ESTADÍSTICAS","◉  RECURSOS","▦  CATÁLOGOS","⚙  CONFIGURACIÓN"};
   for(String q:sm){Button x=bt(q);x.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);x.setTextSize(10);if(q.contains("SEMANA")){x.setTextColor(YELLOW);GradientDrawable sg=shape(PANEL2,dp(10));sg.setStroke(dp(1),YELLOW);x.setBackground(sg);}side.addView(x,new LinearLayout.LayoutParams(-1,dp(43)));if(q.contains("SEMANA"))x.setOnClickListener(v->{favoritesOnly=false;render();});if(q.equals("□  DÍA"))x.setOnClickListener(v->dayView());if(q.contains("PEDIDOS PENDIENTES"))x.setOnClickListener(v->pendingTrips());if(q.contains("SEMANA"))x.setOnLongClickListener(v->{copyWeek();return true;});if(q.contains("HISTORIAL"))x.setOnClickListener(v->history());if(q.contains("ESTADÍSTICAS"))x.setOnClickListener(v->stats());if(q.contains("CONFIGURACIÓN"))x.setOnClickListener(v->toolsMenu());if(q.contains("RECURSOS"))x.setOnClickListener(v->resources());if(q.contains("SERVICIOS"))x.setOnClickListener(v->services());if(q.contains("CATÁLOGOS")||q.contains("EMPRESAS")||q.contains("CHOFERES")||q.contains("CAMIONES")||q.contains("ACOPLADOS")||q.contains("CONTENEDORES")||q.contains("MATERIALES")||q.contains("DESTINOS"))x.setOnClickListener(v->catalogs());}
   TextView eco=tx("♻\nMÁS LOGÍSTICA\nMÁS RECICLAJE\nUN MUNDO MÁS LIMPIO",10,GREEN);side.addView(eco,new LinearLayout.LayoutParams(-1,0,1));
   shell.addView(side,new LinearLayout.LayoutParams(dp(180),-1));
  }

  LinearLayout main=new LinearLayout(this);main.setOrientation(LinearLayout.VERTICAL);main.setPadding(dp(8),dp(4),dp(8),dp(4));shell.addView(main,new LinearLayout.LayoutParams(0,-1,1));
  LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);
  String[] ns={"+ NUEVO VIAJE","RESUMEN SEMANA","VER DÍA","★ FAVORITOS","COPIAR SEMANA","BUSCAR","ESTADÍSTICAS","CATÁLOGOS","BACKUP"};
  for(String q:ns){Button x=bt(q);if(q.startsWith("+")){x.setTextColor(Color.BLACK);x.setBackground(shape(YELLOW,dp(12)));}int aw=(widthDp<700?96:(q.startsWith("+")?132:112));actions.addView(x,new LinearLayout.LayoutParams(dp(aw),dp(widthDp>heightDp()?44:50)));if(q.startsWith("+"))x.setOnClickListener(v->chooseDay());else if(q.equals("RESUMEN SEMANA"))x.setOnClickListener(v->weekMovementSummary());else if(q.equals("VER DÍA"))x.setOnClickListener(v->dayView());else if(q.startsWith("★"))x.setOnClickListener(v->{favoritesOnly=!favoritesOnly;render();});else if(q.equals("COPIAR SEMANA"))x.setOnClickListener(v->copyWeek());else if(q.equals("BUSCAR"))x.setOnClickListener(v->searchTrips());else if(q.startsWith("EST"))x.setOnClickListener(v->stats());else if(q.equals("CATÁLOGOS"))x.setOnClickListener(v->catalogs());else if(q.equals("BACKUP")){x.setOnClickListener(v->backupMenu());}}
  HorizontalScrollView as=new HorizontalScrollView(this);as.setHorizontalScrollBarEnabled(false);as.addView(actions);main.addView(as);

  LinearLayout weekbar=new LinearLayout(this);weekbar.setGravity(Gravity.CENTER_VERTICAL);Button p=bt("‹"),h=bt("HOY"),n=bt("›");weekTitle=tx("",16,WHITE);weekTitle.setGravity(Gravity.CENTER);weekTitle.setTypeface(null,1);weekbar.addView(p,new LinearLayout.LayoutParams(dp(54),dp(48)));weekbar.addView(weekTitle,new LinearLayout.LayoutParams(0,dp(54),1));weekbar.addView(h,new LinearLayout.LayoutParams(dp(72),dp(48)));weekbar.addView(n,new LinearLayout.LayoutParams(dp(54),dp(48)));main.addView(weekbar);

  kpiBar=new LinearLayout(this);kpiBar.setOrientation(LinearLayout.HORIZONTAL); // KPIs quedan disponibles para estadísticas, no ocupan espacio permanente en semana
  daysHeader=new LinearLayout(this);daysHeader.setOrientation(LinearLayout.HORIZONTAL);main.addView(daysHeader,new LinearLayout.LayoutParams(-1,dp(42)));
  ScrollView sv=new ScrollView(this);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setFillViewport(true);board=new LinearLayout(this);board.setOrientation(LinearLayout.VERTICAL);hs.addView(board);sv.addView(hs);main.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  foot=tx("",12,MUTED);foot.setBackground(shape(PANEL,dp(10)));main.addView(foot);TextView maker=tx("∞  PROYECTO CERO  ∞\nsoftware & proyectos",7,Color.rgb(170,145,75));maker.setGravity(Gravity.CENTER);maker.setTypeface(null,1);main.addView(maker,new LinearLayout.LayoutParams(-1,dp(30)));
  if(widthDp>=1100){
   detailPanel=new LinearLayout(this);detailPanel.setOrientation(LinearLayout.VERTICAL);detailPanel.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable dg=shape(Color.rgb(13,24,17),dp(16));dg.setStroke(dp(1),GREEN);detailPanel.setBackground(dg);
   TextView dh=tx("DETALLE DEL VIAJE",16,GREEN);dh.setTypeface(null,1);detailPanel.addView(dh);
   detailPanel.addView(tx("Seleccioná un viaje del tablero para abrir su ficha operativa.",12,MUTED));
   detailBody=tx("\nEMPRESA\n—\n\nFECHA / HORA\n—\n\nCHOFER / CAMIÓN\n—\n\nSERVICIO / DESTINO\n—\n\nMATERIALES\n—\n\nOBSERVACIONES\n—\n\nFOTOS / EVIDENCIAS\n—",11,WHITE);detailPanel.addView(detailBody,new LinearLayout.LayoutParams(-1,0,1));
   LinearLayout quick=new LinearLayout(this);quick.setOrientation(LinearLayout.HORIZONTAL);
   detailState=bt("ESTADO");detailEdit=bt("EDITAR");detailMove=bt("MOVER");quick.addView(detailState,new LinearLayout.LayoutParams(0,dp(48),1));quick.addView(detailEdit,new LinearLayout.LayoutParams(0,dp(48),1));quick.addView(detailMove,new LinearLayout.LayoutParams(0,dp(48),1));detailPanel.addView(quick);
   detailOpen=bt("ABRIR FICHA COMPLETA");detailOpen.setTextColor(Color.BLACK);detailOpen.setBackground(shape(YELLOW,dp(12)));detailOpen.setEnabled(false);detailState.setEnabled(false);detailEdit.setEnabled(false);detailMove.setEnabled(false);
   detailOpen.setOnClickListener(v->{if(selectedRow>=0&&selectedIdx>=0)detail(selectedRow,selectedDay,selectedIdx,trips(selectedRow,selectedDay)[selectedIdx]);});
   detailState.setOnClickListener(v->{if(selectedRow>=0&&selectedIdx>=0){String z=trips(selectedRow,selectedDay)[selectedIdx];stateDialog(selectedRow,selectedDay,selectedIdx,z);}});
   detailEdit.setOnClickListener(v->{if(selectedRow>=0&&selectedIdx>=0){String z=trips(selectedRow,selectedDay)[selectedIdx];editTrip(selectedRow,selectedDay,selectedIdx,z);}});
   detailMove.setOnClickListener(v->{if(selectedRow>=0&&selectedIdx>=0){String z=trips(selectedRow,selectedDay)[selectedIdx];moveTrip(selectedRow,selectedDay,selectedIdx,z);}});
   detailPanel.addView(detailOpen,new LinearLayout.LayoutParams(-1,dp(52)));
   shell.addView(detailPanel,new LinearLayout.LayoutParams(dp(260),-1));
  }
  p.setOnClickListener(v->{week.add(Calendar.WEEK_OF_YEAR,-1);render();});n.setOnClickListener(v->{week.add(Calendar.WEEK_OF_YEAR,1);render();});h.setOnClickListener(v->{week=Calendar.getInstance();render();});
  setContentView(root);render();
 }
 Calendar monday(){Calendar c=(Calendar)week.clone();int d=c.get(Calendar.DAY_OF_WEEK);c.add(Calendar.DATE,d==Calendar.SUNDAY?-6:Calendar.MONDAY-d);return c;}
 String wk(){return new SimpleDateFormat("yyyyMMdd",Locale.US).format(monday().getTime());}
 String key(int row,int day){return wk()+"_"+row+"_"+day;}
 String[] trips(int row,int day){String raw=db.getString(key(row,day),"");return raw.length()==0?new String[0]:raw.split("\\|\\|",-1);}
 String summary(int row,int day){String[] a=trips(row,day);if(a.length==0)return "＋";if(a.length>2){int rea=0,curso=0,otros=0;for(String v:a){if(v.contains("REALIZADO"))rea++;else if(v.contains("EN CURSO"))curso++;else otros++;}return a.length+" VIAJES\n✓ "+rea+"   ▶ "+curso+"   • "+otros+" restantes\nTOCAR PARA VER";}StringBuilder z=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)z.append("\n────────\n");String v=a[i];String[] p=v.split(" · ");String time=p.length>0?p[0]:"";String service=p.length>1?p[1]:"VIAJE";String state=v.contains("REALIZADO")?"✓":v.contains("EN CURSO")?"▶":v.contains("CANCELADO")?"×":v.contains("REPROGRAMADO")?"↻":v.contains("PEDIDO PENDIENTE")?"!":"•";z.append(state).append(" ").append(time).append("\n").append(service);}return z.toString();}
 String tripSummary(String v){String[] p=v.split(" · ");String time=p.length>0?p[0].trim():"";String service=p.length>1?p[1]:"VIAJE";String state=v.contains("REALIZADO")?"✓ REALIZADO":v.contains("EN CURSO")?"▶ EN CURSO":v.contains("CANCELADO")?"× CANCELADO":v.contains("REPROGRAMADO")?"↻ REPROGRAMADO":v.contains("PEDIDO PENDIENTE")?"! PENDIENTE":"• PROGRAMADO";String extra="";for(int i=2;i<p.length;i++){String q=p[i];boolean st=false;for(String z:states)if(q.equals(z))st=true;if(!st&&!q.startsWith("OBS:")){extra=q;break;}}String out=time+" · "+service+"\n"+state;if(extra.length()>0)out+=" · "+(extra.length()>28?extra.substring(0,28)+"…":extra);return out;}
 boolean conflict(int row,int day,String v){return conflictDetail(row,day,v).length()>0;}
 String assignedFrom(String v,String[] catalog){for(String q:catalog)if(q!=null&&!q.startsWith("ELEGIR")&&v.contains(" · "+q+" · "))return q;return "";}
 String conflictDetail(int row,int day,String v){return conflictDetailCore(row,day,v,true);}
 String conflictDetailNew(int row,int day,String v){return conflictDetailCore(row,day,v,false);}
 String conflictDetailCore(int row,int day,String v,boolean skipSelf){String time=tripTime(v);if(!time.matches("\\d{2}:\\d{2}"))return "";String driver=assignedFrom(v,drivers),truck=assignedFrom(v,trucks),trailer=assignedFrom(v,trailers);if(driver.length()==0&&truck.length()==0&&trailer.length()==0)return "";boolean skipped=false;for(int r=0;r<companies.length;r++)for(String x:trips(r,day)){if(skipSelf&&!skipped&&r==row&&x.equals(v)){skipped=true;continue;}if(!tripTime(x).equals(time))continue;String xd=assignedFrom(x,drivers),xt=assignedFrom(x,trucks),xa=assignedFrom(x,trailers);if(driver.length()>0&&driver.equals(xd))return "Chofer "+driver+" ya asignado a "+companies[r]+" a las "+time+".";if(truck.length()>0&&truck.equals(xt))return "Camión "+truck+" ya asignado a "+companies[r]+" a las "+time+".";if(trailer.length()>0&&trailer.equals(xa))return "Acoplado "+trailer+" ya asignado a "+companies[r]+" a las "+time+".";}return "";}
 void appendTrip(int row,int day,String v){String k=key(row,day);ArrayList<String> a=new ArrayList<>(Arrays.asList(trips(row,day)));a.add(v);Collections.sort(a,(x,y)->tripTime(x).compareTo(tripTime(y)));db.edit().putString(k,android.text.TextUtils.join("||",a)).apply();}
 String tripTime(String v){String[] p=v.split(" · ");String t=p.length>0?p[0].trim():"99:99";return t.matches("\\d{2}:\\d{2}")?t:"99:99";}
 void normalizeDay(int row,int day){String[] raw=trips(row,day);ArrayList<String> a=new ArrayList<>(Arrays.asList(raw));Collections.sort(a,(x,y)->tripTime(x).compareTo(tripTime(y)));db.edit().putString(key(row,day),android.text.TextUtils.join("||",a)).apply();}
 void saveHistory(String action,String detail){String old=db.getString("history","");String now=new SimpleDateFormat("dd/MM HH:mm",new Locale("es","AR")).format(new Date());db.edit().putString("history",now+" · "+action+" · "+detail+"\n"+old).apply();}
 int weeklyCount(int r){int n=0;for(int d=0;d<7;d++)n+=trips(r,d).length;return n;}
 int[] displayOrder(){Integer[] o=new Integer[companies.length];for(int i=0;i<o.length;i++)o[i]=i;Arrays.sort(o,(a,b)->{boolean fa=db.getBoolean("fav_"+a,false),fb=db.getBoolean("fav_"+b,false);if(fa!=fb)return fa?-1:1;int ca=weeklyCount(a),cb=weeklyCount(b);if(ca!=cb)return Integer.compare(cb,ca);return companies[a].compareToIgnoreCase(companies[b]);});int[] z=new int[o.length];for(int i=0;i<o.length;i++)z[i]=o[i];return z;}
  void render(){
  Calendar c=monday(),e=(Calendar)c.clone();e.add(Calendar.DATE,6);SimpleDateFormat f=new SimpleDateFormat("dd/MM",new Locale("es","AR"));weekTitle.setText("SEMANA  "+f.format(c.getTime())+" — "+f.format(e.getTime()));
  board.removeAllViews();daysHeader.removeAllViews();
  int total=0,done=0,pending=0,course=0,repro=0,cancel=0;
  int screenDp=(int)(getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density);
  boolean landscape=getResources().getConfiguration().orientation==android.content.res.Configuration.ORIENTATION_LANDSCAPE;int usable=Math.max(320,screenDp-20);int companyW=landscape?Math.max(120,usable/6):Math.max(82,usable/4);int dayW=Math.max(38,(usable-companyW)/7);int rowH=landscape?62:68;
  TextView eh=tx("EMPRESA",10,GREEN);eh.setGravity(Gravity.CENTER_VERTICAL);eh.setTypeface(null,1);eh.setBackground(shape(PANEL,dp(8)));daysHeader.addView(eh,new LinearLayout.LayoutParams(dp(companyW),dp(42)));
  Calendar hc=monday();for(int di=0;di<7;di++){Calendar dc=(Calendar)hc.clone();dc.add(Calendar.DATE,di);String num=new SimpleDateFormat("dd",Locale.US).format(dc.getTime());TextView q=tx(days[di]+"\n"+num,screenDp<500?7:9,di==6?RED:(di==5?YELLOW:GREEN));q.setGravity(Gravity.CENTER);q.setTypeface(null,1);GradientDrawable hg=shape(PANEL,dp(8));hg.setStroke(dp(1),Color.rgb(45,65,50));q.setBackground(hg);daysHeader.addView(q,new LinearLayout.LayoutParams(dp(dayW),dp(42)));}
  int visibleCompanies=0;for(int ord:displayOrder()){int r=ord;visibleCompanies++;if(favoritesOnly&&!db.getBoolean("fav_"+r,false))continue;LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(1),0,dp(1));final int rr=r;
   TextView cn=tx((db.getBoolean("fav_"+r,false)?"★ ":"☆ ")+companies[r]+(weeklyCount(r)>0?"\n"+weeklyCount(r)+" viaje"+(weeklyCount(r)>1?"s":""):""),screenDp<500?8:(screenDp<900?9:11),WHITE);GradientDrawable ng=shape(PANEL,dp(8));ng.setStroke(dp(1),weeklyCount(r)>0?GREEN:Color.rgb(45,65,50));cn.setBackground(ng);cn.setGravity(Gravity.CENTER_VERTICAL);cn.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(companies[rr]).setItems(new String[]{db.getBoolean("fav_"+rr,false)?"★ QUITAR DE FAVORITAS":"☆ MARCAR COMO FAVORITA","VER VIAJES DE LA EMPRESA"},(a,which)->{if(which==0){boolean nv=!db.getBoolean("fav_"+rr,false);db.edit().putBoolean("fav_"+rr,nv).apply();Toast.makeText(this,nv?"★ Favorita guardada":"Favorita quitada",Toast.LENGTH_SHORT).show();render();}else companyTrips(rr);}).show());cn.setOnLongClickListener(v->{boolean nv=!db.getBoolean("fav_"+rr,false);db.edit().putBoolean("fav_"+rr,nv).apply();Toast.makeText(this,nv?"★ Favorita guardada":"Favorita quitada",Toast.LENGTH_SHORT).show();render();return true;});row.addView(cn,new LinearLayout.LayoutParams(dp(companyW),dp(rowH)));
   for(int d=0;d<7;d++){String val=db.getString(key(r,d),"");Button cell=bt(val.length()==0?"＋":summary(r,d));cell.setTextSize(screenDp<900?8:10);if(val.length()>0){int sc=stateColor(val);cell.setTextColor(sc);GradientDrawable cg=shape(PANEL2,dp(8));cg.setStroke(dp(1),sc);cell.setBackground(cg);}final int dd=d;cell.setOnClickListener(v->{if(db.getString(key(rr,dd),"").isEmpty())form(companies[rr],dd);else companyDayTrips(rr,dd);});cell.setOnLongClickListener(v->{if(!db.getString(key(rr,dd),"").isEmpty())tripMenu(rr,dd);return true;});if(val.length()==0){cell.setTextColor(Color.rgb(85,115,92));GradientDrawable eg=shape(Color.rgb(14,23,17),dp(8));eg.setStroke(dp(1),Color.rgb(35,55,41));cell.setBackground(eg);}row.addView(cell,new LinearLayout.LayoutParams(dp(dayW),dp(rowH)));for(String tv:trips(r,d)){total++;if(tv.contains("REALIZADO"))done++;else if(tv.contains("EN CURSO"))course++;else if(tv.contains("REPROGRAMADO"))repro++;else if(tv.contains("CANCELADO"))cancel++;else pending++;}}
   board.addView(row);
  }

  int sinChofer=0,sinCamion=0;for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String tv:trips(r,d)){boolean tieneChofer=false,tieneCamion=false;for(String q:drivers)if(!q.startsWith("ELEGIR")&&tv.contains(q))tieneChofer=true;for(String q:trucks)if(!q.startsWith("ELEGIR")&&tv.contains(q))tieneCamion=true;if(!tv.contains("CANCELADO")&&!tieneChofer)sinChofer++;if(!tv.contains("CANCELADO")&&!tieneCamion)sinCamion++;}updateKpis();foot.setText("Viajes "+total+"   •   Realizados "+done+"   •   En curso "+course+"   •   Pendientes "+pending+"   •   Sin chofer "+sinChofer+"   •   Sin camión "+sinCamion);
 }
 void companyDayTrips(int r,int d){String[] ts=trips(r,d);Calendar dc=monday();dc.add(Calendar.DATE,d);SimpleDateFormat df=new SimpleDateFormat("dd/MM",new Locale("es","AR"));int realizados=0,curso=0,pendientes=0,programados=0,reprogramados=0,cancelados=0;for(String t:ts){if(t.contains("REALIZADO"))realizados++;else if(t.contains("EN CURSO"))curso++;else if(t.contains("PEDIDO PENDIENTE"))pendientes++;else if(t.contains("REPROGRAMADO"))reprogramados++;else if(t.contains("CANCELADO"))cancelados++;else programados++;}String title=companies[r]+" · "+dayLong[d]+" "+df.format(dc.getTime())+" · "+ts.length+" VIAJE"+(ts.length>1?"S":"");String resumen="Programados: "+programados+"   En curso: "+curso+"   Realizados: "+realizados+"\nPendientes: "+pendientes+"   Reprogramados: "+reprogramados+"   Cancelados: "+cancelados+"\nTocá un viaje para abrirlo.";new AlertDialog.Builder(this).setTitle(title).setMessage(resumen).setItems(ts,(a,i)->detail(r,d,i,ts[i])).setPositiveButton("+ AGREGAR OTRO VIAJE",(a,b)->form(companies[r],d)).setNegativeButton("Cerrar",null).show();}
 void companyTrips(int r){ArrayList<String> items=new ArrayList<>();ArrayList<Integer> refs=new ArrayList<>();Calendar m=monday();SimpleDateFormat df=new SimpleDateFormat("dd/MM",new Locale("es","AR"));int rea=0,curso=0,pend=0,prog=0,repro=0,canc=0,sinD=0,sinT=0;for(int d=0;d<7;d++){Calendar dc=(Calendar)m.clone();dc.add(Calendar.DATE,d);String[] aa=trips(r,d);for(int i=0;i<aa.length;i++){String v=aa[i];items.add(dayLong[d]+" "+df.format(dc.getTime())+"\n"+tripSummary(v));refs.add(d*1000+i);if(v.contains("REALIZADO"))rea++;else if(v.contains("EN CURSO"))curso++;else if(v.contains("PEDIDO PENDIENTE"))pend++;else if(v.contains("REPROGRAMADO"))repro++;else if(v.contains("CANCELADO"))canc++;else prog++;if(!v.contains("CANCELADO")){if(assignedFrom(v,drivers).length()==0)sinD++;if(assignedFrom(v,trucks).length()==0)sinT++;}}}if(items.size()==0){new AlertDialog.Builder(this).setTitle(companies[r]).setMessage("Sin viajes esta semana").setPositiveButton("+ AGREGAR VIAJE",(x,y)->chooseCompanyDay(r)).setNegativeButton("Cerrar",null).show();return;}StringBuilder resumen=new StringBuilder();for(int d=0;d<7;d++){int n=trips(r,d).length;if(n>0){Calendar dc=(Calendar)m.clone();dc.add(Calendar.DATE,d);resumen.append(dayLong[d]).append(" ").append(df.format(dc.getTime())).append(" · ").append(n).append(" viaje").append(n>1?"s":"").append("\n");}}resumen.append("\nPROGRAMADOS ").append(prog).append(" · EN CURSO ").append(curso).append(" · REALIZADOS ").append(rea).append("\nPENDIENTES ").append(pend).append(" · REPROGRAMADOS ").append(repro).append(" · CANCELADOS ").append(canc);if(sinD>0||sinT>0)resumen.append("\n\nASIGNACIÓN PENDIENTE · sin chofer ").append(sinD).append(" · sin camión ").append(sinT);new AlertDialog.Builder(this).setTitle(companies[r]+" · "+items.size()+" VIAJE"+(items.size()>1?"S":"")+" ESTA SEMANA").setMessage(resumen.toString()+"\n\nTocá un viaje para abrirlo:").setItems(items.toArray(new String[0]),(x,n)->{int z=refs.get(n),d=z/1000,i=z%1000;detail(r,d,i,trips(r,d)[i]);}).setPositiveButton("+ AGREGAR VIAJE",(x,y)->chooseCompanyDay(r)).setNegativeButton("Cerrar",null).show();}
 void chooseCompanyDay(int r){Calendar m=monday();String[] opts=new String[7];SimpleDateFormat df=new SimpleDateFormat("dd/MM",new Locale("es","AR"));for(int d=0;d<7;d++){Calendar dc=(Calendar)m.clone();dc.add(Calendar.DATE,d);int n=trips(r,d).length;opts[d]=dayLong[d]+" "+df.format(dc.getTime())+(n>0?"  ·  "+n+" viaje"+(n>1?"s":""):"  ·  sin viajes");}new AlertDialog.Builder(this).setTitle(companies[r]+" · elegir día").setItems(opts,(a,d)->form(companies[r],d)).setNegativeButton("Cancelar",null).show();}
 void selectCellTrip(int r,int d){String[] a=trips(r,d);if(a.length==0){form(companies[r],d);return;}if(a.length==1){selectTrip(r,d,0);return;}String[] opts=new String[a.length];for(int i=0;i<a.length;i++){String[] p=a[i].split(" · ");String tm=p.length>0?p[0]:"";String sv=p.length>1?p[1]:"VIAJE";String st=a[i].contains("REALIZADO")?"REALIZADO":a[i].contains("EN CURSO")?"EN CURSO":a[i].contains("REPROGRAMADO")?"REPROGRAMADO":a[i].contains("CANCELADO")?"CANCELADO":a[i].contains("PEDIDO PENDIENTE")?"PENDIENTE":"PROGRAMADO";opts[i]=tm+"  ·  "+sv+"  ·  "+st;}new AlertDialog.Builder(this).setTitle(companies[r]+" · "+dayLong[d]).setItems(opts,(x,idx)->selectTrip(r,d,idx)).setNegativeButton("Cerrar",null).show();}
 void selectTrip(int r,int d,int idx){selectedRow=r;selectedDay=d;selectedIdx=idx;if(detailBody==null)return;String[] a=trips(r,d);if(idx<0||idx>=a.length)return;String v=a[idx];String[] p=v.split(" · ");String time=p.length>0?p[0]:"—";String service=p.length>1?p[1]:"VIAJE";String state=v.contains("REALIZADO")?"REALIZADO":v.contains("EN CURSO")?"EN CURSO":v.contains("REPROGRAMADO")?"REPROGRAMADO":v.contains("CANCELADO")?"CANCELADO":v.contains("PEDIDO PENDIENTE")?"PEDIDO PENDIENTE":"PROGRAMADO";String ev=db.getString(evidenceKey(r,d,idx),"");int photos=ev.length()==0?0:ev.split("\\|\\|",-1).length;detailBody.setText("\nEMPRESA\n"+companies[r]+"\n\nDÍA / HORA\n"+days[d]+"  ·  "+time+"\n\nSERVICIO\n"+service+"\n\nESTADO\n"+state+"\n\nDATOS OPERATIVOS\n"+v+"\n\nFOTOS / EVIDENCIAS\n"+photos+" archivo"+(photos==1?"":"s"));detailBody.setTextColor(stateColor(v));if(detailOpen!=null)detailOpen.setEnabled(true);if(detailState!=null)detailState.setEnabled(true);if(detailEdit!=null)detailEdit.setEnabled(true);if(detailMove!=null)detailMove.setEnabled(true);}
 void dayView(){String[] opts=new String[7];Calendar c=(Calendar)week.clone();for(int d=0;d<7;d++){Calendar z=(Calendar)c.clone();z.add(Calendar.DAY_OF_MONTH,d);opts[d]=dayLong[d]+"  "+new SimpleDateFormat("dd/MM",Locale.getDefault()).format(z.getTime());}new AlertDialog.Builder(this).setTitle("VER DÍA · "+weekTitle.getText()).setItems(opts,(a,d)->showDay(d)).show();}
 void showDay(int d){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(8),dp(12),dp(12));int companiesMoved=0,totalTrips=0;for(int r:displayOrder()){String[] aa=trips(r,d);if(aa.length==0)continue;companiesMoved++;totalTrips+=aa.length;int rea=0,curso=0,pend=0,otros=0;for(String v:aa){if(v.contains("REALIZADO"))rea++;else if(v.contains("EN CURSO"))curso++;else if(v.contains("PEDIDO PENDIENTE"))pend++;else otros++;}final int rr=r;TextView card=tx(companies[r]+"  ·  "+aa.length+" VIAJE"+(aa.length>1?"S":"")+"\n✓ "+rea+"  ▶ "+curso+"  • "+pend+" pendientes  ·  "+otros+" otros",13,WHITE);GradientDrawable g=shape(PANEL2,dp(12));g.setStroke(dp(1),GREEN);card.setBackground(g);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setOnClickListener(v->companyDayTrips(rr,d));box.addView(card,new LinearLayout.LayoutParams(-1,dp(70)));}if(companiesMoved==0)box.addView(tx("No hubo movimiento para este día.",14,MUTED));ScrollView sc=new ScrollView(this);sc.addView(box);Calendar fecha=monday();fecha.add(Calendar.DATE,d);String fechaTxt=new SimpleDateFormat("dd/MM",new Locale("es","AR")).format(fecha.getTime());new AlertDialog.Builder(this).setTitle(dayLong[d]+" "+fechaTxt+" · "+companiesMoved+" EMPRESAS · "+totalTrips+" VIAJES").setView(sc).setPositiveButton("+ NUEVO VIAJE",(x,y)->form("",d)).setNegativeButton("Cerrar",null).show();}
 void searchTrips(){final EditText q=new EditText(this);q.setHint("Empresa, material, chofer, patente...");new AlertDialog.Builder(this).setTitle("Buscar viajes").setView(q).setPositiveButton("BUSCAR",(a,b)->{String needle=q.getText().toString().trim().toLowerCase(new Locale("es","AR"));ArrayList<String> items=new ArrayList<>();ArrayList<int[]> refs=new ArrayList<>();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++){String[] ts=trips(r,d);for(int j=0;j<ts.length;j++){String v=ts[j];String hay=(companies[r]+" "+days[d]+" "+v).toLowerCase(new Locale("es","AR"));if(needle.length()>0&&hay.contains(needle)){items.add(companies[r]+" · "+days[d]+" · "+tripTime(v)+"\n"+v);refs.add(new int[]{r,d,j});}}}if(items.isEmpty()){new AlertDialog.Builder(this).setTitle("Resultados").setMessage("Sin resultados").setPositiveButton("Cerrar",null).show();return;}new AlertDialog.Builder(this).setTitle("RESULTADOS · "+items.size()).setItems(items.toArray(new String[0]),(x,n)->{int[] z=refs.get(n);detail(z[0],z[1],z[2],trips(z[0],z[1])[z[2]]);}).setNegativeButton("Cerrar",null).show();}).setNegativeButton("Cancelar",null).show();}
 void chooseDay(){new AlertDialog.Builder(this).setTitle("¿Qué día es el viaje?").setItems(days,(a,d)->form("",d)).show();}
 void form(String company,int day){form(company,day,-1);}
 void form(String company,int day,int sourceRow){
  ScrollView sc=new ScrollView(this);LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(18),dp(8),dp(18),dp(18));sc.addView(f);
  String[] companyOptions=new String[companies.length+1];companyOptions[0]="ELEGIR EMPRESA";for(int ci=0;ci<companies.length;ci++)companyOptions[ci+1]=(db.getBoolean("fav_"+ci,false)?"★ ":"")+companies[ci];Spinner co=spin(companyOptions);if(sourceRow>=0&&sourceRow<companies.length)co.setSelection(sourceRow+1);else if(company!=null&&company.length()>0){int cr=findCompany(company);if(cr>=0)co.setSelection(cr+1);}f.addView(label("Empresa / cliente"));f.addView(co);
  f.addView(label("Programación"));EditText tm=new EditText(this);tm.setHint("ELEGIR HORA · tocar");tm.setFocusable(false);tm.setOnClickListener(v->{Calendar now=Calendar.getInstance();new TimePickerDialog(this,(vv,h,m)->tm.setText(String.format(Locale.US,"%02d:%02d",h,m)),now.get(Calendar.HOUR_OF_DAY),now.get(Calendar.MINUTE),true).show();});f.addView(tm);
  f.addView(label("Operación"));Spinner ser=spin(new String[]{"ELEGIR ACCIÓN","RETIRO DE MATERIALES","SERVICIO DE RETIRO","RETIRO + SERVICIO"});f.addView(ser);
  Spinner subtype=spin(new String[]{"ELEGIR TIPO / DETALLE"});f.addView(label("Tipo / detalle del retiro"));f.addView(subtype);
  
  f.addView(label("Asignación de recursos"));Spinner drv=spin(drivers);f.addView(label("Chofer"));f.addView(drv);Spinner tr=spin(trucks);f.addView(label("Camión"));f.addView(tr);
  Spinner trail=spin(trailers);f.addView(label("Acoplado"));f.addView(trail);
  Spinner cont=spin(new String[]{"ELEGIR CONTENEDOR","GDE 30 ROLL","MED 20 ROLL","CHICO 15 ROLL","GDE 18 PORTA","CHICO 8 PORTA"});f.addView(label("Contenedor"));f.addView(cont);
  Spinner dest=spin(withFirst("ELEGIR DESTINO",destinations));TextView destLabel=label("Destino");f.addView(destLabel);f.addView(dest);Spinner disp=spin(new String[]{"DISPOSICIÓN PENDIENTE","DISPOSICIÓN SÍ","DISPOSICIÓN NO"});TextView dispLabel=label("Disposición final");f.addView(dispLabel);f.addView(disp);disp.setVisibility(View.GONE);dispLabel.setVisibility(View.GONE);
  Spinner st=spin(states);st.setSelection(1);f.addView(label("Estado del viaje"));f.addView(st);TextView hint=tx("Chofer, camión, acoplado, contenedor y destino pueden quedar sin asignar y completarse después.",10,MUTED);f.addView(hint);
  TextView mat=tx("Seleccionar materiales adicionales",13,GREEN);mat.setBackground(shape(PANEL2,12));final boolean[] sel=new boolean[materials.length];final String[] chosen={""};mat.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Materiales").setMultiChoiceItems(materials,sel,(a,i,on)->sel[i]=on).setPositiveButton("ACEPTAR",(a,b)->{StringBuilder z=new StringBuilder();for(int i=0;i<materials.length;i++)if(sel[i]){if(z.length()>0)z.append(", ");z.append(materials[i]);}chosen[0]=z.toString();mat.setText(chosen[0].length()==0?"Seleccionar materiales":chosen[0]);}).show());TextView matLabel=label("Materiales del viaje (selección múltiple · opcional al crear)");f.addView(matLabel);f.addView(mat);ser.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){String[] opts=(pos==2||pos==3)?new String[]{"ELEGIR TIPO / DETALLE","LINNER","FLEJES","RSU","OTRO"}:new String[]{"ELEGIR TIPO / DETALLE"};subtype.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,opts));boolean mats=(pos==1||pos==3);mat.setVisibility(mats?View.VISIBLE:View.GONE);matLabel.setVisibility(mats?View.VISIBLE:View.GONE);boolean retiro=(pos==2||pos==3);disp.setVisibility(retiro?View.VISIBLE:View.GONE);dispLabel.setVisibility(retiro?View.VISIBLE:View.GONE);destLabel.setText(retiro?"Destino / disposición":"Destino (opcional)");}});EditText obs=new EditText(this);obs.setHint("Observaciones");f.addView(obs);
  int target=day<0?0:day;new AlertDialog.Builder(this).setTitle("NUEVO VIAJE  ·  "+days[target]).setView(sc).setPositiveButton("GUARDAR",(x,y)->{if(co.getSelectedItemPosition()==0){Toast.makeText(this,"Elegí una empresa",Toast.LENGTH_LONG).show();return;}if(ser.getSelectedItemPosition()==0){Toast.makeText(this,"Elegí RETIRO, SERVICIO o AMBOS",Toast.LENGTH_LONG).show();return;}int row=co.getSelectedItemPosition()-1;String enteredCompany=companies[row];String val=(tm.getText().length()>0?tm.getText()+" ":"")+ser.getSelectedItem().toString()+(subtype.getSelectedItemPosition()>0?" · "+subtype.getSelectedItem().toString():"")+(chosen[0].length()>0?" · MATERIALES: "+chosen[0]:"")+(drv.getSelectedItemPosition()>0?" · "+drv.getSelectedItem():"")+(tr.getSelectedItemPosition()>0?" · "+tr.getSelectedItem():"")+(trail.getSelectedItemPosition()>0?" · "+trail.getSelectedItem():"")+(cont.getSelectedItemPosition()>0?" · "+cont.getSelectedItem():"")+(dest.getSelectedItemPosition()>0?" · "+dest.getSelectedItem():"")+((ser.getSelectedItemPosition()==2||ser.getSelectedItemPosition()==3)?" · "+disp.getSelectedItem():"")+(obs.getText().length()>0?" · OBS: "+obs.getText():"")+" · "+st.getSelectedItem().toString();String cd=conflictDetailNew(row,target,val);if(cd.length()>0){new AlertDialog.Builder(this).setTitle("CONFLICTO DE RECURSOS").setMessage(cd+"\n\nEl viaje NO fue guardado. Cambiá horario o recurso.").setPositiveButton("CORREGIR",null).show();return;}appendTrip(row,target,val);saveHistory("ALTA",companies[row]+" · "+days[target]+" · "+val);render();}).setNegativeButton("Cancelar",null).show();
 }
 TextView label(String s){TextView v=tx(s,11,MUTED);v.setTypeface(null,1);return v;}
 String[] withFirst(String first,String[] src){String[] z=new String[src.length+1];z[0]=first;System.arraycopy(src,0,z,1,src.length);return z;}
 Spinner spin(String[] a){Spinner s=new Spinner(this);ArrayAdapter<String>x=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a);s.setAdapter(x);return s;}
 int findCompany(String s){return ensureCompany(s);}
 void tripMenu(int r,int d){String[] list=trips(r,d);if(list.length>1){String[] names=new String[list.length];for(int i=0;i<list.length;i++)names[i]=(i+1)+" · "+list[i];new AlertDialog.Builder(this).setTitle(companies[r]+" · "+days[d]+" · VIAJES").setItems(names,(a,i)->tripActions(r,d,i)).setNegativeButton("+ NUEVO VIAJE",(a,b)->form(companies[r],d)).show();return;}tripActions(r,d,0);}
 void tripActions(int r,int d,int idx){String[] list=trips(r,d);if(list.length==0||idx<0||idx>=list.length)return;String v=list[idx];String[] a={"VER VIAJE","CAMBIAR ESTADO","COMPLETAR / EDITAR DATOS","REPROGRAMAR","DUPLICAR","FOTOS / EVIDENCIAS","VER EVIDENCIAS","GENERAR PDF","CANCELAR VIAJE","BORRAR VIAJE"};new AlertDialog.Builder(this).setTitle(companies[r]+" · "+days[d]+"\n"+v).setItems(a,(x,w)->{if(w==0)detail(r,d,idx,v);if(w==1)stateDialog(r,d,idx,v);if(w==2)editTrip(r,d,idx,v);if(w==3)moveTrip(r,d,idx,v);if(w==4)duplicateTrip(r,d,idx,v);if(w==5)photos(r,d,idx);if(w==6)openEvidence(r,d,idx);if(w==7)makePdf(r,d,v);if(w==8){String nv=v;for(String z:states)nv=nv.replace(z,"CANCELADO");if(!nv.contains("CANCELADO"))nv+=" · CANCELADO";replaceTrip(r,d,idx,nv);saveHistory("CANCELADO",companies[r]+" · "+days[d]);render();}if(w==9)deleteTrip(r,d,idx,v);}).show();}
 void deleteTrip(int r,int d,int idx,String v){new AlertDialog.Builder(this).setTitle("BORRAR VIAJE").setMessage("¿Borrar definitivamente este viaje?\n\n"+companies[r]+" · "+days[d]+"\n"+v).setPositiveButton("BORRAR",(a,b)->{String[] all=trips(r,d);if(idx<0||idx>=all.length)return;ArrayList<String> keep=new ArrayList<>();for(int i=0;i<all.length;i++)if(i!=idx)keep.add(all[i]);db.edit().putString(key(r,d),android.text.TextUtils.join("||",keep)).remove(evidenceKey(r,d,idx)).apply();saveHistory("BORRADO",companies[r]+" · "+days[d]+" · "+v);render();Toast.makeText(this,"Viaje borrado",Toast.LENGTH_SHORT).show();}).setNegativeButton("NO",null).show();}
 void duplicateTrip(int r,int d,int idx,String v){new AlertDialog.Builder(this).setTitle("DUPLICAR VIAJE").setMessage("Elegí el día de destino. Se copiarán también las evidencias del viaje.").setItems(dayLong,(x,nd)->{String nv=v;for(String z:states)if(nv.contains(z)&&!z.equals("PEDIDO PENDIENTE"))nv=nv.replace(z,"PROGRAMADO");if(conflict(r,nd,nv)){new AlertDialog.Builder(this).setTitle("Conflicto detectado").setMessage("Chofer o camión ocupado en ese horario. No se duplicó.").setPositiveButton("OK",null).show();return;}String ev=db.getString(evidenceKey(r,d,idx),db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,""));appendTrip(r,nd,nv);if(ev.length()>0){String[] dest=trips(r,nd);for(int j=0;j<dest.length;j++)if(dest[j].equals(nv)){db.edit().putString(evidenceKey(r,nd,j),ev).apply();break;}}saveHistory("DUPLICADO",companies[r]+" · "+days[d]+" → "+days[nd]);render();Toast.makeText(this,"Viaje duplicado en "+dayLong[nd],Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancelar",null).show();}
 void replaceTrip(int r,int d,int idx,String nv){String[] a=trips(r,d);if(idx<0||idx>=a.length)return;String old=a[idx];String oldKey="evidence_"+wk()+"_"+r+"_"+d+"_"+Integer.toHexString(old.hashCode());String evidence=db.getString(oldKey,db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,""));a[idx]=nv;StringBuilder z=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)z.append("||");z.append(a[i]);}SharedPreferences.Editor ed=db.edit().putString(key(r,d),z.toString());if(evidence.length()>0){String newKey="evidence_"+wk()+"_"+r+"_"+d+"_"+Integer.toHexString(nv.hashCode());ed.putString(newKey,evidence);if(!newKey.equals(oldKey))ed.remove(oldKey);}ed.apply();}
 void quickState(int r,int d,int idx,String v,String target){String nv=v;boolean found=false;for(String z:states)if(nv.contains(z)){nv=nv.replace(z,target);found=true;break;}if(!found)nv=nv+" · "+target;replaceTrip(r,d,idx,nv);saveHistory("ESTADO RÁPIDO",companies[r]+" · "+target);render();Toast.makeText(this,companies[r]+" → "+target,Toast.LENGTH_SHORT).show();}
 void stateDialog(int r,int d,int idx,String v){new AlertDialog.Builder(this).setTitle("Cambiar estado").setItems(states,(x,i)->{String nv=v;for(String z:states)nv=nv.replace(z,states[i]);replaceTrip(r,d,idx,nv);saveHistory("ESTADO",companies[r]+" · "+states[i]);render();}).show();}
 void editTrip(int r,int d,int idx,String old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(8),dp(14),dp(8));box.addView(tx("Podés completar o corregir cualquier dato. El viaje puede seguir PENDIENTE aunque falten asignaciones.",11,MUTED));final EditText e=new EditText(this);e.setText(old);e.setMinLines(5);box.addView(e);new AlertDialog.Builder(this).setTitle("COMPLETAR / EDITAR VIAJE").setView(box).setPositiveButton("GUARDAR",(a,b)->{String nv=e.getText().toString().trim();if(nv.length()==0){Toast.makeText(this,"Usá BORRAR VIAJE si querés eliminarlo",Toast.LENGTH_LONG).show();return;}String cd=conflictDetail(r,d,nv);if(cd.length()>0&&!nv.equals(old)){new AlertDialog.Builder(this).setTitle("Conflicto detectado").setMessage(cd+"\n\nNo se guardó el cambio.").setPositiveButton("OK",null).show();return;}replaceTrip(r,d,idx,nv);normalizeDay(r,d);saveHistory("COMPLETAR / EDITAR",companies[r]+" · "+days[d]+" · "+nv);render();}).setNegativeButton("Cancelar",null).show();}
 void moveTrip(int r,int oldDay,int idx,String v){new AlertDialog.Builder(this).setTitle("Mover viaje a otro día").setItems(days,(a,newDay)->{if(newDay==oldDay)return;String nv=v.replace("PROGRAMADO","REPROGRAMADO");if(conflict(r,newDay,nv)){new AlertDialog.Builder(this).setTitle("Conflicto detectado").setMessage("El chofer o camión ya está asignado en ese horario. El viaje permanece en su día original.").setPositiveButton("OK",null).show();return;}String[] old=trips(r,oldDay);if(idx<0||idx>=old.length)return;String oldEv=db.getString(evidenceKey(r,oldDay,idx),db.getString("photo_"+wk()+"_"+r+"_"+oldDay+"_"+idx,""));ArrayList<String> keep=new ArrayList<>();for(int i=0;i<old.length;i++)if(i!=idx)keep.add(old[i]);db.edit().putString(key(r,oldDay),android.text.TextUtils.join("||",keep)).apply();appendTrip(r,newDay,nv);if(oldEv.length()>0){String[] moved=trips(r,newDay);int ni=-1;for(int q=0;q<moved.length;q++)if(moved[q].equals(nv)){ni=q;break;}if(ni>=0)db.edit().putString(evidenceKey(r,newDay,ni),oldEv).apply();saveHistory("EVIDENCIA MIGRADA",companies[r]+" · "+days[newDay]);}saveHistory("MOVER / REPROGRAMAR",companies[r]+" · "+days[oldDay]+" → "+days[newDay]);render();}).show();}
 void detail(int r,int d,int idx,String v){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(14),dp(18),dp(18));GradientDrawable headBg=shape(PANEL,dp(16));headBg.setStroke(dp(2),stateColor(v));TextView title=tx(companies[r],22,WHITE);title.setTypeface(null,1);title.setBackground(headBg);title.setPadding(dp(16),dp(14),dp(16),dp(14));box.addView(title);TextView sub=tx(days[d]+"  ·  "+weekTitle.getText(),13,GREEN);sub.setTypeface(null,1);box.addView(sub);String[] parts=v.split(" · ");String[] labels={"HORA / SERVICIO","DETALLE","ASIGNACIÓN","VEHÍCULO","RECURSO","CONTENEDOR","DESTINO","OBSERVACIONES","ESTADO"};for(int i=0;i<parts.length;i++){String lab=i<labels.length?labels[i]:"DATO "+(i+1);TextView l=tx(lab,10,MUTED);l.setTypeface(null,1);box.addView(l);TextView value=tx(parts[i],15,WHITE);value.setBackground(shape(PANEL2,dp(10)));value.setPadding(dp(12),dp(9),dp(12),dp(9));box.addView(value);}String raw=db.getString(evidenceKey(r,d,idx),db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,""));int ev=raw.length()==0?0:raw.split("\\|\\|").length;TextView evidence=tx("FOTOS / EVIDENCIAS   "+ev+(ev>0?"  ·  TOCAR PARA VER":"  ·  SIN ARCHIVOS"),13,ev>0?GREEN:MUTED);evidence.setTypeface(null,1);evidence.setPadding(dp(12),dp(14),dp(12),dp(14));evidence.setBackground(shape(PANEL2,dp(10)));evidence.setOnClickListener(x->{if(ev>0)openEvidence(r,d,idx);else photos(r,d,idx);});evidence.setOnLongClickListener(x->{photos(r,d,idx);return true;});box.addView(evidence);LinearLayout actionBox=new LinearLayout(this);actionBox.setOrientation(LinearLayout.VERTICAL);String[] an={"EN CURSO","REALIZADO","ESTADO","EDITAR","REPROGRAMAR","MÁS"};for(int row=0;row<2;row++){LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);for(int col=0;col<3;col++){String name=an[row*3+col];Button b=bt(name);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(52),1);bp.setMargins(dp(3),dp(3),dp(3),dp(3));actions.addView(b,bp);if(name.equals("EN CURSO"))b.setOnClickListener(x->quickState(r,d,idx,v,"EN CURSO"));if(name.equals("REALIZADO"))b.setOnClickListener(x->quickState(r,d,idx,v,"REALIZADO"));if(name.equals("ESTADO"))b.setOnClickListener(x->stateDialog(r,d,idx,v));if(name.equals("EDITAR"))b.setOnClickListener(x->editTrip(r,d,idx,v));if(name.equals("REPROGRAMAR"))b.setOnClickListener(x->moveTrip(r,d,idx,v));if(name.equals("MÁS"))b.setOnClickListener(x->moreTripActions(r,d,idx,v));}actionBox.addView(actions);}box.addView(actionBox);ScrollView sc=new ScrollView(this);sc.addView(box);new AlertDialog.Builder(this).setTitle("FICHA OPERATIVA DEL VIAJE").setView(sc).setPositiveButton("Cerrar",null).show();}
 void moreTripActions(int r,int d,int idx,String v){String[] a={"FOTOS / EVIDENCIAS","GENERAR PDF","DUPLICAR VIAJE","CANCELAR VIAJE"};new AlertDialog.Builder(this).setTitle("MÁS ACCIONES").setItems(a,(x,n)->{if(n==0)photos(r,d,idx);if(n==1)makePdf(r,d,v);if(n==2)duplicateTrip(r,d,idx,v);if(n==3)new AlertDialog.Builder(this).setTitle("CANCELAR VIAJE").setMessage("¿Confirmás cancelar este viaje?").setPositiveButton("CANCELAR VIAJE",(q,w)->quickState(r,d,idx,v,"CANCELADO")).setNegativeButton("Volver",null).show();}).setNegativeButton("Cerrar",null).show();}
 String evidenceKey(int r,int d,int idx){String[] a=trips(r,d);String v=(idx>=0&&idx<a.length)?a[idx]:"";return "evidence_"+wk()+"_"+r+"_"+d+"_"+Integer.toHexString(v.hashCode());}
 void openEvidence(int r,int d,int idx){String raw=db.getString(evidenceKey(r,d,idx),db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,""));if(raw.length()==0){new AlertDialog.Builder(this).setTitle("Evidencias").setMessage("Este viaje todavía no tiene fotos adjuntas.").setPositiveButton("OK",null).show();return;}String[] us=raw.split("\\|\\|");String[] labels=new String[us.length];for(int i=0;i<us.length;i++)labels[i]="Evidencia "+(i+1);new AlertDialog.Builder(this).setTitle("EVIDENCIAS · "+us.length).setItems(labels,(a,n)->evidenceActions(r,d,idx,us,n)).setNegativeButton("Cerrar",null).show();}
 void evidenceActions(int r,int d,int idx,String[] us,int n){String[] ops={"ABRIR","ELIMINAR","VOLVER A GALERÍA"};new AlertDialog.Builder(this).setTitle("Evidencia "+(n+1)).setItems(ops,(x,k)->{if(k==0){try{Intent it=new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(us[n]));it.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(it);}catch(Exception ex){new AlertDialog.Builder(this).setMessage("No se pudo abrir esta evidencia.").setPositiveButton("OK",null).show();}}else if(k==1){new AlertDialog.Builder(this).setTitle("Eliminar evidencia").setMessage("¿Quitar esta foto del viaje?").setPositiveButton("ELIMINAR",(a,b)->{ArrayList<String> keep=new ArrayList<>();for(int j=0;j<us.length;j++)if(j!=n)keep.add(us[j]);db.edit().putString(evidenceKey(r,d,idx),android.text.TextUtils.join("||",keep)).apply();saveHistory("EVIDENCIA ELIMINADA",companies[r]+" · "+days[d]);Toast.makeText(this,"Evidencia eliminada",Toast.LENGTH_SHORT).show();}).setNegativeButton("Cancelar",null).show();}else openEvidence(r,d,idx);}).show();}
 void photos(int r,int d,int idx){String k=evidenceKey(r,d,idx);String raw=db.getString(k,db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,""));int count=raw.length()==0?0:raw.split("\\|\\|").length;String[] ops=count>0?new String[]{"VER EVIDENCIAS · "+count,"+ AGREGAR FOTO"}:new String[]{"+ AGREGAR FOTO"};new AlertDialog.Builder(this).setTitle("FOTOS / EVIDENCIAS").setItems(ops,(a,n)->{if(count>0&&n==0){openEvidence(r,d,idx);return;}photoRow=r;photoDay=d;photoIdx=idx;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,700);}).setNegativeButton("Cerrar",null).show();}
 void makePdf(int r,int d,String v){try{PdfDocument pdf=new PdfDocument();PdfDocument.Page page=pdf.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Paint p=new Paint();android.graphics.Canvas c=page.getCanvas();p.setColor(Color.rgb(18,70,42));c.drawRect(0,0,595,105,p);p.setColor(Color.WHITE);p.setTextSize(28);p.setFakeBoldText(true);c.drawText("FAVORABLE",42,48,p);p.setTextSize(14);p.setFakeBoldText(false);c.drawText("VIAJES · LOGÍSTICA QUE TRANSFORMA",42,76,p);p.setColor(Color.rgb(35,35,35));p.setTextSize(18);p.setFakeBoldText(true);c.drawText("FICHA OPERATIVA DEL VIAJE",42,140,p);p.setFakeBoldText(false);p.setTextSize(13);int y=178;c.drawText("EMPRESA / CLIENTE",42,y,p);y+=20;p.setTextSize(18);p.setFakeBoldText(true);c.drawText(companies[r],42,y,p);p.setFakeBoldText(false);p.setTextSize(13);y+=32;Calendar dc=monday();dc.add(Calendar.DATE,d);String fecha=new SimpleDateFormat("EEEE dd/MM/yyyy",new Locale("es","AR")).format(dc.getTime()).toUpperCase(new Locale("es","AR"));c.drawText(fecha,42,y,p);y+=34;String[] parts=v.split(" · ");String[] labels={"HORA / SERVICIO","DETALLE","CHOFER / ASIGNACIÓN","VEHÍCULO","RECURSO","CONTENEDOR","DESTINO","OBSERVACIONES","ESTADO"};for(int i=0;i<parts.length&&y<720;i++){p.setTextSize(10);p.setFakeBoldText(true);c.drawText(i<labels.length?labels[i]:"DATO",42,y,p);y+=17;p.setTextSize(13);p.setFakeBoldText(false);String val=parts[i];if(val.length()>72)val=val.substring(0,72)+"…";c.drawText(val,42,y,p);y+=29;}p.setTextSize(10);p.setColor(Color.DKGRAY);c.drawText("Generado por FAVORABLE VIAJES · "+new SimpleDateFormat("dd/MM/yyyy HH:mm",new Locale("es","AR")).format(new Date()),42,805,p);pdf.finishPage(page);File dir=new File(getExternalFilesDir(null),"pdf");dir.mkdirs();String safe=companies[r].replaceAll("[^A-Za-z0-9_-]","_");File out=new File(dir,"Favorable_Viaje_"+safe+"_"+new SimpleDateFormat("yyyyMMdd_HHmm",Locale.US).format(new Date())+".pdf");FileOutputStream os=new FileOutputStream(out);pdf.writeTo(os);os.close();pdf.close();saveHistory("PDF",out.getName());new AlertDialog.Builder(this).setTitle("PDF generado").setMessage("Ficha creada correctamente:\n"+out.getAbsolutePath()).setPositiveButton("OK",null).show();}catch(Exception e){Toast.makeText(this,"No se pudo generar PDF",Toast.LENGTH_LONG).show();}}
 void backupMenu(){String[] a={"CREAR BACKUP AHORA","RESTAURAR ÚLTIMO BACKUP"};new AlertDialog.Builder(this).setTitle("BACKUP FAVORABLE VIAJES").setItems(a,(x,n)->{if(n==0)backup();else confirmRestore();}).setNegativeButton("Cancelar",null).show();}
 void backup(){try{File dir=new File(getExternalFilesDir(null),"backup");dir.mkdirs();File out=new File(dir,"FavorableViajes_"+new SimpleDateFormat("yyyyMMdd_HHmm",Locale.US).format(new Date())+".txt");FileOutputStream os=new FileOutputStream(out);StringBuilder z=new StringBuilder();for(Map.Entry<String,?> e:db.getAll().entrySet())z.append(e.getKey()).append("=").append(String.valueOf(e.getValue())).append("\n");os.write(z.toString().getBytes("UTF-8"));os.close();saveHistory("BACKUP",out.getName());new AlertDialog.Builder(this).setTitle("Backup creado").setMessage(out.getAbsolutePath()).setPositiveButton("OK",null).show();}catch(Exception e){Toast.makeText(this,"Error de backup",Toast.LENGTH_LONG).show();}}
 void restoreLatest(){try{File dir=new File(getExternalFilesDir(null),"backup");File[] fs=dir.listFiles();if(fs==null||fs.length==0){Toast.makeText(this,"No hay backups",Toast.LENGTH_SHORT).show();return;}Arrays.sort(fs,(a,b)->Long.compare(b.lastModified(),a.lastModified()));BufferedReader br=new BufferedReader(new InputStreamReader(new FileInputStream(fs[0]),"UTF-8"));SharedPreferences.Editor ed=db.edit().clear();String line;while((line=br.readLine())!=null){int p=line.indexOf('=');if(p>0){String k=line.substring(0,p),v=line.substring(p+1);if(k.startsWith("fav_"))ed.putBoolean(k,Boolean.parseBoolean(v));else ed.putString(k,v);}}br.close();ed.apply();saveHistory("RESTAURADO",fs[0].getName());render();Toast.makeText(this,"Backup restaurado",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"No se pudo restaurar",Toast.LENGTH_LONG).show();}}
 void history(){String h=db.getString("history","Sin movimientos todavía.");ScrollView sc=new ScrollView(this);TextView v=tx(h,13,WHITE);v.setBackgroundColor(BG);sc.addView(v);new AlertDialog.Builder(this).setTitle("Historial / trazabilidad").setView(sc).setPositiveButton("Cerrar",null).show();}
 void toolsMenu(){String[] x={"CREAR BACKUP AHORA","RESTAURAR ÚLTIMO BACKUP","RESUMEN POR EMPRESA","HISTORIAL","DIAGNÓSTICO"};new AlertDialog.Builder(this).setTitle("HERRAMIENTAS / CONFIGURACIÓN").setItems(x,(a,n)->{if(n==0)backup();if(n==1)confirmRestore();if(n==2)companySummary();if(n==3)history();if(n==4)diagnostics();}).setNegativeButton("Cerrar",null).show();}
 void confirmRestore(){new AlertDialog.Builder(this).setTitle("RESTAURAR BACKUP").setMessage("La restauración reemplazará los datos actuales por el último backup disponible. ¿Continuar?").setPositiveButton("RESTAURAR",(a,b)->restoreLatest()).setNegativeButton("Cancelar",null).show();}
 void diagnostics(){int tripCount=0,ev=0,conflicts=0;for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++){String[] a=trips(r,d);tripCount+=a.length;for(int j=0;j<a.length;j++){String raw=db.getString(evidenceKey(r,d,j),"");if(raw.length()>0)ev+=raw.split("\\|\\|").length;if(conflictDetail(r,d,a[j]).length()>0)conflicts++;}}conflicts=conflicts/2;File bd=new File(getExternalFilesDir(null),"backup");File pd=new File(getExternalFilesDir(null),"pdf");int backups=bd.listFiles()==null?0:bd.listFiles().length,pdfs=pd.listFiles()==null?0:pd.listFiles().length;String status=conflicts==0?"OPERATIVO · SIN CONFLICTOS":"ATENCIÓN · "+conflicts+" CONFLICTO(S)";new AlertDialog.Builder(this).setTitle("DIAGNÓSTICO FAVORABLE VIAJES").setMessage("Semana: "+wk()+"\\nEmpresas: "+companies.length+"\\nViajes cargados: "+tripCount+"\\nEvidencias vinculadas: "+ev+"\\nConflictos de recursos: "+conflicts+"\\nBackups locales: "+backups+"\\nPDF generados: "+pdfs+"\\n\\nEstado local: "+status).setPositiveButton("Cerrar",null).show();}
 void weekMovementSummary(){LinearLayout wrap=new LinearLayout(this);wrap.setOrientation(LinearLayout.VERTICAL);wrap.setPadding(dp(6),dp(6),dp(6),dp(6));int sw=widthDpSafe();int cw=Math.max(90,sw/4),dw=Math.max(46,(sw-cw-28)/5);LinearLayout head=new LinearLayout(this);TextView he=tx("EMPRESA",9,GREEN);he.setGravity(Gravity.CENTER);head.addView(he,new LinearLayout.LayoutParams(dp(cw),dp(42)));Calendar mm=monday();for(int d=0;d<5;d++){Calendar z=(Calendar)mm.clone();z.add(Calendar.DATE,d);TextView h=tx(days[d]+"\n"+new SimpleDateFormat("dd",Locale.US).format(z.getTime()),8,GREEN);h.setGravity(Gravity.CENTER);h.setBackground(shape(PANEL,dp(6)));head.addView(h,new LinearLayout.LayoutParams(dp(dw),dp(42)));}wrap.addView(head);int moved=0,total=0;for(int r:displayOrder()){int monFri=0;for(int d=0;d<5;d++)monFri+=trips(r,d).length;if(monFri==0)continue;moved++;total+=monFri;final int rr=r;LinearLayout row=new LinearLayout(this);TextView name=tx((db.getBoolean("fav_"+r,false)?"★ ":"")+companies[r],8,WHITE);name.setGravity(Gravity.CENTER_VERTICAL);name.setBackground(shape(PANEL,dp(6)));name.setOnClickListener(v->companyTrips(rr));row.addView(name,new LinearLayout.LayoutParams(dp(cw),dp(58)));for(int d=0;d<5;d++){String[] aa=trips(r,d);final int dd=d;Button cell=bt(aa.length==0?"—":(aa.length==1?tripTime(aa[0]):aa.length+" VIAJES"));cell.setTextSize(7);cell.setTextColor(aa.length==0?MUTED:GREEN);cell.setBackground(shape(PANEL2,dp(6)));cell.setOnClickListener(v->{if(trips(rr,dd).length==0)form(companies[rr],dd,rr);else companyDayTrips(rr,dd);});row.addView(cell,new LinearLayout.LayoutParams(dp(dw),dp(58)));}wrap.addView(row);}if(moved==0)wrap.addView(tx("No hubo movimiento de lunes a viernes.",13,MUTED));HorizontalScrollView hs=new HorizontalScrollView(this);hs.addView(wrap);ScrollView vs=new ScrollView(this);vs.addView(hs);new AlertDialog.Builder(this).setTitle("SEMANA · LUNES A VIERNES · "+moved+" EMPRESAS · "+total+" VIAJES").setView(vs).setPositiveButton("Cerrar",null).show();}
 void companySummary(){StringBuilder z=new StringBuilder("SEMANA "+wk()+"\nRESUMEN POR EMPRESA\n\n");for(int r=0;r<companies.length;r++){int n=0;for(int d=0;d<7;d++)n+=trips(r,d).length;if(n>0)z.append(companies[r]).append("  ·  ").append(n).append(" viaje(s)\n");}new AlertDialog.Builder(this).setTitle("Resumen semanal por empresa").setMessage(z.toString()).setPositiveButton("Cerrar",null).show();}
 void catalogs(){String[] a={"EMPRESAS · "+companies.length,"CHOFERES · "+drivers.length,"CAMIONES · "+trucks.length,"ACOPLADOS · "+(trailers.length-1),"CONTENEDORES · 5","MATERIALES · "+materials.length,"DESTINOS · "+destinations.length};new AlertDialog.Builder(this).setTitle("CATÁLOGOS OPERATIVOS").setItems(a,(x,i)->{if(i==0)companyCatalog();else{String[] v=i==1?drivers:i==2?trucks:i==3?trailers:i==4?new String[]{"GDE 30 ROLL · 30 m³","MED 20 ROLL · 20 m³","CHICO 15 ROLL · 15 m³","GDE 18 PORTA · 18 m³","CHICO 8 PORTA · 8 m³"}:i==5?materials:destinations;new AlertDialog.Builder(this).setTitle(a[i]).setItems(v,null).setPositiveButton("Cerrar",null).show();}}).setNegativeButton("Cerrar",null).show();}
 void companyCatalog(){ArrayList<String> list=new ArrayList<>(Arrays.asList(companies));Collections.sort(list,String.CASE_INSENSITIVE_ORDER);String[] a=list.toArray(new String[0]);new AlertDialog.Builder(this).setTitle("EMPRESAS · "+a.length).setItems(a,(x,i)->{int r=findCompany(a[i]);boolean fav=db.getBoolean("fav_"+r,false);new AlertDialog.Builder(this).setTitle(a[i]).setMessage((fav?"★ FAVORITA":"Empresa activa")+"\nViajes esta semana: "+weeklyCount(r)).setPositiveButton(fav?"QUITAR FAVORITA":"★ FAVORITA",(q,w)->{db.edit().putBoolean("fav_"+r,!fav).apply();render();}).setNegativeButton("Cerrar",null).show();}).setPositiveButton("+ AGREGAR",(x,w)->{final EditText e=new EditText(this);e.setHint("Nombre de empresa");new AlertDialog.Builder(this).setTitle("Nueva empresa").setView(e).setPositiveButton("GUARDAR",(q,z)->{if(e.getText().toString().trim().length()>0){ensureCompany(e.getText().toString());render();}}).setNegativeButton("Cancelar",null).show();}).setNegativeButton("Cerrar",null).show();}
 void copyWeek(){new AlertDialog.Builder(this).setTitle("COPIAR SEMANA").setMessage("Se copiarán los viajes a la semana siguiente sin borrar los que ya existan.\n\nLos viajes normales pasarán como PROGRAMADO. Los PEDIDOS PENDIENTES conservarán su estado.").setPositiveButton("COPIAR Y COMBINAR",(x,y)->{String from=wk();Calendar next=monday();next.add(Calendar.DATE,7);SimpleDateFormat kf=new SimpleDateFormat("yyyyMMdd",Locale.US);String to=kf.format(next.getTime());int n=0,existing=0,skipped=0;SharedPreferences.Editor ed=db.edit();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++){String[] src=trips(r,d);if(src.length==0)continue;String targetKey="w"+to+"_r"+r+"_d"+d;String rawTarget=db.getString(targetKey,"");ArrayList<String> z=new ArrayList<>();if(rawTarget.length()>0){z.addAll(Arrays.asList(rawTarget.split("\\|\\|",-1)));existing+=z.size();}for(String v:src){String nv=v.contains("PEDIDO PENDIENTE")?v:v.replace("REALIZADO","PROGRAMADO").replace("EN CURSO","PROGRAMADO").replace("REPROGRAMADO","PROGRAMADO").replace("CANCELADO","PROGRAMADO");if(z.contains(nv)){skipped++;continue;}z.add(nv);n++;}Collections.sort(z,(a,b)->tripTime(a).compareTo(tripTime(b)));ed.putString(targetKey,android.text.TextUtils.join("||",z));}ed.apply();saveHistory("COPIAR SEMANA",from+" → "+to+" · "+n+" nuevos · "+skipped+" duplicados omitidos · "+existing+" preexistentes");Toast.makeText(this,n+" nuevos · "+skipped+" duplicados omitidos · "+existing+" existentes conservados",Toast.LENGTH_LONG).show();}).setNegativeButton("Cancelar",null).show();}
 void pendingTrips(){ArrayList<String> items=new ArrayList<>();ArrayList<int[]> refs=new ArrayList<>();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++){String[] a=trips(r,d);for(int j=0;j<a.length;j++)if(a[j].contains("PEDIDO PENDIENTE")){items.add(companies[r]+" · "+dayLong[d]+" · "+tripTime(a[j])+"\n"+a[j]);refs.add(new int[]{r,d,j});}}if(items.isEmpty()){new AlertDialog.Builder(this).setTitle("PEDIDOS PENDIENTES").setMessage("No hay pedidos pendientes esta semana.").setPositiveButton("Cerrar",null).show();return;}new AlertDialog.Builder(this).setTitle("PEDIDOS PENDIENTES · "+items.size()).setItems(items.toArray(new String[0]),(x,n)->{int[] z=refs.get(n);detail(z[0],z[1],z[2],trips(z[0],z[1])[z[2]]);}).setNegativeButton("Cerrar",null).show();}
 void resources(){int driversUsed=0,trucksUsed=0;HashSet<String> ds=new HashSet<>(),ts=new HashSet<>();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String v:trips(r,d)){for(String q:drivers)if(!q.startsWith("ELEGIR")&&v.contains(q))ds.add(q);for(String q:trucks)if(!q.startsWith("ELEGIR")&&v.contains(q))ts.add(q);}driversUsed=ds.size();trucksUsed=ts.size();int sinD=0,sinT=0;for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String v:trips(r,d)){if(v.contains("CANCELADO"))continue;boolean hd=false,ht=false;for(String q:drivers)if(!q.startsWith("ELEGIR")&&v.contains(q))hd=true;for(String q:trucks)if(!q.startsWith("ELEGIR")&&v.contains(q))ht=true;if(!hd)sinD++;if(!ht)sinT++;}new AlertDialog.Builder(this).setTitle("RECURSOS · SEMANA").setMessage("Choferes utilizados: "+driversUsed+" / "+(drivers.length-1)+"\nCamiones utilizados: "+trucksUsed+" / "+trucks.length+"\nViajes sin chofer: "+sinD+"\nViajes sin camión: "+sinT+"\nAcoplados disponibles: "+(trailers.length-1)+"\nContenedores catalogados: 5").setPositiveButton("VER SIN ASIGNAR",(a,b)->unassignedTrips()).setNegativeButton("Cerrar",null).show();}
 void unassignedTrips(){ArrayList<String> items=new ArrayList<>();ArrayList<int[]> refs=new ArrayList<>();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++){String[] aa=trips(r,d);for(int j=0;j<aa.length;j++){String v=aa[j];if(v.contains("CANCELADO"))continue;boolean hd=false,ht=false;for(String q:drivers)if(!q.startsWith("ELEGIR")&&v.contains(q))hd=true;for(String q:trucks)if(!q.startsWith("ELEGIR")&&v.contains(q))ht=true;if(!hd||!ht){items.add(companies[r]+" · "+dayLong[d]+" · "+tripTime(v)+"\n"+(!hd?"SIN CHOFER":"CHOFER OK")+" · "+(!ht?"SIN CAMIÓN":"CAMIÓN OK"));refs.add(new int[]{r,d,j});}}}if(items.isEmpty()){new AlertDialog.Builder(this).setTitle("SIN ASIGNAR").setMessage("Todos los viajes activos tienen chofer y camión asignados.").setPositiveButton("Cerrar",null).show();return;}new AlertDialog.Builder(this).setTitle("VIAJES SIN ASIGNAR · "+items.size()).setItems(items.toArray(new String[0]),(x,n)->{int[] z=refs.get(n);detail(z[0],z[1],z[2],trips(z[0],z[1])[z[2]]);}).setNegativeButton("Cerrar",null).show();}
 void services(){new AlertDialog.Builder(this).setTitle("SERVICIOS").setItems(new String[]{"RETIRO DE MATERIALES","SERVICIO DE RETIRO · LINNERS / FLEJES / RSU"},null).setPositiveButton("Cerrar",null).show();}
 void stats(){int total=0,rea=0,prog=0,curso=0,repro=0,canc=0,ped=0,retiros=0,servicios=0,mixtos=0,sinHora=0;int[] daily=new int[7];HashMap<String,Integer> matCount=new HashMap<>(),driverCount=new HashMap<>(),truckCount=new HashMap<>(),companyCount=new HashMap<>(),destCount=new HashMap<>();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String v:trips(r,d)){total++;daily[d]++;companyCount.put(companies[r],companyCount.containsKey(companies[r])?companyCount.get(companies[r])+1:1);if(v.contains("REALIZADO"))rea++;else if(v.contains("EN CURSO"))curso++;else if(v.contains("REPROGRAMADO"))repro++;else if(v.contains("CANCELADO"))canc++;else if(v.contains("PEDIDO PENDIENTE"))ped++;else prog++;if(v.contains("RETIRO + SERVICIO"))mixtos++;else if(v.contains("RETIRO DE MATERIALES"))retiros++;else if(v.contains("SERVICIO DE RETIRO"))servicios++;if(tripTime(v).equals("99:99"))sinHora++;for(String q:materials)if(v.contains(q))matCount.put(q,matCount.containsKey(q)?matCount.get(q)+1:1);for(String q:drivers)if(!q.startsWith("ELEGIR")&&v.contains(q))driverCount.put(q,driverCount.containsKey(q)?driverCount.get(q)+1:1);for(String q:trucks)if(!q.startsWith("ELEGIR")&&v.contains(q))truckCount.put(q,truckCount.containsKey(q)?truckCount.get(q)+1:1);for(String q:destinations)if(v.contains(q))destCount.put(q,destCount.containsKey(q)?destCount.get(q)+1:1);}ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(8),dp(12),dp(18));sv.addView(box);TextView kpi=tx("VIAJES  "+total+"     REALIZADOS  "+rea+"     PENDIENTES  "+ped+"\nEN CURSO  "+curso+"     REPROGRAMADOS  "+repro+"     CANCELADOS  "+canc+"\nSIN HORA  "+sinHora,12,WHITE);kpi.setPadding(dp(12),dp(12),dp(12),dp(12));kpi.setBackground(shape(PANEL,dp(12)));box.addView(kpi);box.addView(section("VIAJES POR DÍA"));box.addView(barChart(days,daily));box.addView(section("TIPO DE OPERACIÓN"));box.addView(barChart(new String[]{"RETIRO","SERVICIO","AMBOS"},new int[]{retiros,servicios,mixtos}));box.addView(section("ESTADO DE VIAJES"));box.addView(barChart(new String[]{"REAL.","CURSO","PROG.","PEND.","REPRO.","CANC."},new int[]{rea,curso,prog,ped,repro,canc}));box.addView(section("EMPRESAS CON MÁS MOVIMIENTO"));box.addView(rankingView(companyCount,8));box.addView(section("MATERIALES MÁS MOVIDOS"));box.addView(rankingView(matCount,8));box.addView(section("CHOFERES CON MÁS VIAJES"));box.addView(rankingView(driverCount,8));box.addView(section("CAMIONES CON MÁS VIAJES"));box.addView(rankingView(truckCount,8));box.addView(section("DESTINOS MÁS UTILIZADOS"));box.addView(rankingView(destCount,8));new AlertDialog.Builder(this).setTitle("ESTADÍSTICAS · "+weekTitle.getText()).setView(sv).setPositiveButton("Cerrar",null).show();}
 TextView section(String t){TextView v=tx(t,12,GREEN);v.setTypeface(null,1);v.setPadding(0,dp(16),0,dp(6));return v;}
 View barChart(String[] names,int[] vals){LinearLayout chart=new LinearLayout(this);chart.setOrientation(LinearLayout.VERTICAL);int max=1;for(int v:vals)if(v>max)max=v;for(int i=0;i<names.length;i++){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView n=tx(names[i],9,MUTED);row.addView(n,new LinearLayout.LayoutParams(dp(72),dp(30)));LinearLayout track=new LinearLayout(this);track.setBackground(shape(PANEL2,dp(6)));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,dp(14),1);row.addView(track,tp);TextView fill=new TextView(this);fill.setBackground(shape(GREEN,dp(6)));track.addView(fill,new LinearLayout.LayoutParams(0,-1,vals[i]));if(vals[i]<max)track.addView(new Space(this),new LinearLayout.LayoutParams(0,-1,max-vals[i]));TextView num=tx(""+vals[i],10,WHITE);num.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);row.addView(num,new LinearLayout.LayoutParams(dp(34),dp(30)));chart.addView(row);}return chart;}
 View rankingView(HashMap<String,Integer> map,int maxRows){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);ArrayList<Map.Entry<String,Integer>> a=new ArrayList<>(map.entrySet());Collections.sort(a,(x,y)->Integer.compare(y.getValue(),x.getValue()));if(a.isEmpty()){box.addView(tx("Sin datos",10,MUTED));return box;}int mx=a.get(0).getValue();for(int i=0;i<Math.min(maxRows,a.size());i++){Map.Entry<String,Integer> e=a.get(i);LinearLayout row=new LinearLayout(this);TextView n=tx((i+1)+". "+e.getKey(),9,WHITE);row.addView(n,new LinearLayout.LayoutParams(0,dp(28),1));TextView v=tx(""+e.getValue(),10,GREEN);v.setTypeface(null,1);row.addView(v,new LinearLayout.LayoutParams(dp(38),dp(28)));box.addView(row);}return box;}
 void appendTop(StringBuilder m,HashMap<String,Integer> map,int max){ArrayList<Map.Entry<String,Integer>> a=new ArrayList<>(map.entrySet());Collections.sort(a,(x,y)->Integer.compare(y.getValue(),x.getValue()));if(a.isEmpty()){m.append("Sin datos\n");return;}for(int i=0;i<Math.min(max,a.size());i++)m.append(i+1).append(". ").append(a.get(i).getKey()).append(" · ").append(a.get(i).getValue()).append("\n");}
}
