package com.favorable.viajes;

import android.app.*; import android.os.*; import android.graphics.Color; import android.graphics.drawable.GradientDrawable;
import android.content.*; import android.view.*; import android.graphics.pdf.PdfDocument; import android.graphics.Paint; import java.io.*; import android.view.inputmethod.InputMethodManager; import android.widget.*;
import java.text.*; import java.util.*;

public class MainActivity extends Activity {
 final int BG=Color.rgb(8,13,10),PANEL=Color.rgb(20,29,23),PANEL2=Color.rgb(29,40,32),GREEN=Color.rgb(122,205,69),WHITE=Color.WHITE,MUTED=Color.rgb(177,190,181),RED=Color.rgb(218,70,70),YELLOW=Color.rgb(239,190,55);
 LinearLayout root,board; TextView weekTitle,foot; int photoRow=-1,photoDay=-1,photoIdx=-1; Calendar week=Calendar.getInstance(); SharedPreferences db;
 String[] days={"LUN","MAR","MIÉ","JUE","VIE","SÁB","DOM"};
 String[] companies={"ARCOR","BODEGA MONTEVIEJO","HOLCIM","CLIENTES VARIOS"};
 boolean favoritesOnly=false;
 String[] trailers={"SIN ACOPLADO","AE 056 WL · ACOPLADO","CMC 802 · ACOPLADO","TCM 673 · ACOPLADO","TDH 077 · ACOPLADO"};
 String[] materials={"CARTON","VIDRIO","STRECH","TERMOCONTRAIBLE","ALUMINIO","CHATARRA","PET CRISTAL","BIDONES","COLOR"};
 String[] destinations={"RELLENO SANITARIO","HOLCIM","FAVORABLE","OTRO"};
 String[] states={"PEDIDO PENDIENTE","PROGRAMADO","EN CURSO","REALIZADO","REPROGRAMADO","CANCELADO"};
 String[] drivers={"AGUERO EDGARDO JESUS","CATALDO DANIEL HECTOR","CATALDO FRANCO","CATALDO SERGIO JAVIER","FUNES FABIAN ROQUE","GINIOLI MATIAS VICENTE","MELA GERARDO DARIO","OLMOS JUAN CARLOS","SOTELO FRANCO"};
 String[] trucks={"AC 592 VP · IVECO EUROCARGO","AG 824 DR · IVECO TECTOR","AD 604 WN · IVECO DAILY","AD 670 RD · IVECO TECTOR","AE 056 WX · IVECO TECTOR","AF 252 GE · IVECO TECTOR","DOJ 270 · M. BENZ LK","GIP 868 · M. BENZ L","ILH 135 · IVECO DAILY","OIN 428 · FORD CARGO","PQJ 269 · IVECO EUROCARGO","DPI439 · M. BENZ LK","AI 375 JY · IVECO TECTOR"};
 public void onCreate(Bundle b){super.onCreate(b);db=getSharedPreferences("viajes",0);loadCompanies();build();}
 void loadCompanies(){String x=db.getString("catalog_companies","");if(x.length()>0)companies=x.split("\\|",-1);}
 void saveCompanies(){StringBuilder z=new StringBuilder();for(int i=0;i<companies.length;i++){if(i>0)z.append("|");z.append(companies[i]);}db.edit().putString("catalog_companies",z.toString()).apply();}
 int ensureCompany(String name){name=name.trim().toUpperCase(new Locale("es","AR"));for(int i=0;i<companies.length;i++)if(companies[i].equalsIgnoreCase(name))return i;if(name.length()==0)return 0;String[] n=Arrays.copyOf(companies,companies.length+1);n[n.length-1]=name;companies=n;saveCompanies();return n.length-1;}
 protected void onActivityResult(int req,int res,Intent data){super.onActivityResult(req,res,data);if(req==700&&res==RESULT_OK&&data!=null&&data.getData()!=null){try{getContentResolver().takePersistableUriPermission(data.getData(),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}String k=evidenceKey(photoRow,photoDay,photoIdx);String old=db.getString(k,"");db.edit().putString(k,old.length()==0?data.getData().toString():old+"||"+data.getData()).apply();saveHistory("FOTO",companies[photoRow]+" · "+days[photoDay]);Toast.makeText(this,"Evidencia agregada",Toast.LENGTH_SHORT).show();}}
 TextView tx(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(14,10,14,10);return v;}
 GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(11);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setMinHeight(54);b.setPadding(10,6,10,6);b.setBackground(shape(PANEL2,18));return b;}
 int stateColor(String v){if(v.contains("REALIZADO"))return GREEN;if(v.contains("EN CURSO"))return YELLOW;if(v.contains("CANCELADO"))return RED;if(v.contains("REPROGRAMADO"))return Color.rgb(255,145,60);if(v.contains("PEDIDO PENDIENTE"))return Color.rgb(120,170,220);return WHITE;}
 void build(){
  root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(12,10,12,8);root.setBackgroundColor(BG);
  LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView brand=tx("FAVORABLE\nVIAJES",22,GREEN);brand.setTypeface(null,1);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
  Button p=bt("‹"),h=bt("HOY"),n=bt("›");top.addView(p);top.addView(h);top.addView(n);root.addView(top);
  weekTitle=tx("",16,WHITE);weekTitle.setGravity(Gravity.CENTER);weekTitle.setTypeface(null,1);root.addView(weekTitle);
  LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);String[] ns={"+ VIAJE","BUSCAR","★","ESTAD.","HIST.","BACKUP"};
  for(String s:ns){Button x=bt(s);nav.addView(x,new LinearLayout.LayoutParams(0,64,1));if(s.startsWith("+"))x.setOnClickListener(v->chooseDay());if(s.equals("BUSCAR"))x.setOnClickListener(v->searchTrips());if(s.startsWith("EST"))x.setOnClickListener(v->stats());if(s.equals("★"))x.setOnClickListener(v->{favoritesOnly=!favoritesOnly;render();});if(s.startsWith("HIST"))x.setOnClickListener(v->history());if(s.equals("BACKUP")){x.setOnClickListener(v->backup());x.setOnLongClickListener(v->{restoreLatest();return true;});}}
  root.addView(nav);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setFillViewport(true);ScrollView sv=new ScrollView(this);board=new LinearLayout(this);board.setOrientation(LinearLayout.VERTICAL);sv.addView(board);hs.addView(sv);root.addView(hs,new LinearLayout.LayoutParams(-1,0,1));
  foot=tx("",12,MUTED);root.addView(foot);
  p.setOnClickListener(v->{week.add(Calendar.WEEK_OF_YEAR,-1);render();});n.setOnClickListener(v->{week.add(Calendar.WEEK_OF_YEAR,1);render();});h.setOnClickListener(v->{week=Calendar.getInstance();render();});setContentView(root);render();
 }
 Calendar monday(){Calendar c=(Calendar)week.clone();int d=c.get(Calendar.DAY_OF_WEEK);c.add(Calendar.DATE,d==Calendar.SUNDAY?-6:Calendar.MONDAY-d);return c;}
 String wk(){return new SimpleDateFormat("yyyyMMdd",Locale.US).format(monday().getTime());}
 String key(int row,int day){return wk()+"_"+row+"_"+day;}
 String[] trips(int row,int day){String raw=db.getString(key(row,day),"");return raw.length()==0?new String[0]:raw.split("\\|\\|",-1);}
 String summary(int row,int day){String[] a=trips(row,day);if(a.length==0)return "+";StringBuilder z=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)z.append("\n");String v=a[i];String shortv=v.length()>45?v.substring(0,45)+"…":v;z.append(i+1).append(" · ").append(shortv);}return z.toString();}
 boolean conflict(int row,int day,String v){String[] p=v.split(" · ");if(p.length<5)return false;String time=p[0],driver=p.length>3?p[3]:"",truck=p.length>4?p[4]:"";for(int r=0;r<companies.length;r++)for(String x:trips(r,day)){if(r==row&&x.equals(v))continue;if(x.startsWith(time+" ")&&(x.contains(" · "+driver+" · ")||x.contains(" · "+truck+" · ")))return true;}return false;}
 void appendTrip(int row,int day,String v){String k=key(row,day),old=db.getString(k,"");db.edit().putString(k,old.length()==0?v:old+"||"+v).apply();}
 void saveHistory(String action,String detail){String old=db.getString("history","");String now=new SimpleDateFormat("dd/MM HH:mm",new Locale("es","AR")).format(new Date());db.edit().putString("history",now+" · "+action+" · "+detail+"\n"+old).apply();}
 void render(){
  Calendar c=monday(),e=(Calendar)c.clone();e.add(Calendar.DATE,6);SimpleDateFormat f=new SimpleDateFormat("dd/MM",new Locale("es","AR"));weekTitle.setText("SEMANA "+f.format(c.getTime())+" — "+f.format(e.getTime()));
  board.removeAllViews(); TextView legend=tx("ESTADO  ·  Pendiente  |  Programado  |  En curso  |  Realizado  |  Reprogramado  |  Cancelado",12,MUTED);legend.setPadding(14,6,14,12);board.addView(legend);int total=0,done=0,pending=0,course=0,repro=0,cancel=0;
  int screen=getResources().getDisplayMetrics().widthPixels;
  if(screen<850){
   for(int r=0;r<companies.length;r++){if(favoritesOnly&&!db.getBoolean("fav_"+r,false))continue;final int rr=r;
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(16,12,16,14);card.setBackground(shape(PANEL,22));
    TextView cn=tx((db.getBoolean("fav_"+r,false)?"★ ":"")+companies[r],18,WHITE);cn.setTypeface(null,1);cn.setOnLongClickListener(v->{boolean nv=!db.getBoolean("fav_"+rr,false);db.edit().putBoolean("fav_"+rr,nv).apply();render();return true;});card.addView(cn);
    LinearLayout strip=new LinearLayout(this);strip.setOrientation(LinearLayout.HORIZONTAL);strip.setPadding(0,6,0,0);
    for(int d=0;d<7;d++){final int dd=d;String val=db.getString(key(r,d),"");String label=days[d]+"\n"+(val.length()==0?"＋":trips(r,d).length+" VIAJE"+(trips(r,d).length>1?"S":""));Button b=bt(label);if(val.length()>0)b.setTextColor(stateColor(val));b.setOnClickListener(v->{if(db.getString(key(rr,dd),"").isEmpty())form(companies[rr],dd);else tripMenu(rr,dd);});b.setOnLongClickListener(v->{form(companies[rr],dd);return true;});strip.addView(b,new LinearLayout.LayoutParams(0,76,1));for(String tv:trips(r,d)){total++;if(tv.contains("REALIZADO"))done++;else if(tv.contains("EN CURSO"))course++;else if(tv.contains("REPROGRAMADO"))repro++;else if(tv.contains("CANCELADO"))cancel++;else pending++;}}
    card.addView(strip);Space sp=new Space(this);board.addView(card,new LinearLayout.LayoutParams(-1,-2));board.addView(sp,new LinearLayout.LayoutParams(1,10));
   }
  }else{
   LinearLayout hd=new LinearLayout(this);hd.addView(tx("EMPRESA",12,GREEN),new LinearLayout.LayoutParams(250,62));for(String d:days){TextView q=tx(d,12,GREEN);q.setGravity(Gravity.CENTER);hd.addView(q,new LinearLayout.LayoutParams(170,62));}board.addView(hd);
   for(int r=0;r<companies.length;r++){if(favoritesOnly&&!db.getBoolean("fav_"+r,false))continue;LinearLayout row=new LinearLayout(this);final int rr=r;TextView cn=tx((db.getBoolean("fav_"+r,false)?"★ ":"")+companies[r],12,WHITE);cn.setBackground(shape(PANEL,12));cn.setOnLongClickListener(v->{boolean nv=!db.getBoolean("fav_"+rr,false);db.edit().putBoolean("fav_"+rr,nv).apply();render();return true;});row.addView(cn,new LinearLayout.LayoutParams(250,90));for(int d=0;d<7;d++){String val=db.getString(key(r,d),"");Button cell=bt(summary(r,d));if(val.length()>0)cell.setTextColor(stateColor(val));final int dd=d;cell.setOnClickListener(v->{if(db.getString(key(rr,dd),"").isEmpty())form(companies[rr],dd);else tripMenu(rr,dd);});row.addView(cell,new LinearLayout.LayoutParams(170,90));for(String tv:trips(r,d)){total++;if(tv.contains("REALIZADO"))done++;else if(tv.contains("EN CURSO"))course++;else if(tv.contains("REPROGRAMADO"))repro++;else if(tv.contains("CANCELADO"))cancel++;else pending++;}}board.addView(row);}
  }
  foot.setText("Viajes "+total+"   •   Realizados "+done+"   •   En curso "+course+"   •   Pendientes "+pending+"   •   Reprogramados "+repro+"   •   Cancelados "+cancel);
 }
 void searchTrips(){final EditText q=new EditText(this);q.setHint("Empresa, material, chofer, patente...");new AlertDialog.Builder(this).setTitle("Buscar viajes").setView(q).setPositiveButton("BUSCAR",(a,b)->{String needle=q.getText().toString().toLowerCase(new Locale("es","AR"));StringBuilder out=new StringBuilder();for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String v:trips(r,d)){String hay=(companies[r]+" "+days[d]+" "+v).toLowerCase(new Locale("es","AR"));if(hay.contains(needle))out.append(companies[r]).append(" · ").append(days[d]).append("\n").append(v).append("\n\n");}new AlertDialog.Builder(this).setTitle("Resultados").setMessage(out.length()==0?"Sin resultados":out.toString()).setPositiveButton("Cerrar",null).show();}).setNegativeButton("Cancelar",null).show();}
 void chooseDay(){new AlertDialog.Builder(this).setTitle("¿Qué día es el viaje?").setItems(days,(a,d)->form("",d)).show();}
 void form(String company,int day){
  ScrollView sc=new ScrollView(this);LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(28,8,28,8);sc.addView(f);
  EditText co=new EditText(this);co.setHint("Empresa / cliente");co.setText(company);f.addView(co);
  EditText tm=new EditText(this);tm.setHint("Hora · tocar para elegir");tm.setFocusable(false);tm.setOnClickListener(v->{Calendar now=Calendar.getInstance();new TimePickerDialog(this,(vv,h,m)->tm.setText(String.format(Locale.US,"%02d:%02d",h,m)),now.get(Calendar.HOUR_OF_DAY),now.get(Calendar.MINUTE),true).show();});f.addView(tm);
  Spinner ser=spin(new String[]{"RETIRO DE MATERIALES","SERVICIO DE RETIRO"});f.addView(label("Servicio"));f.addView(ser);
  Spinner drv=spin(drivers);f.addView(label("Chofer"));f.addView(drv);Spinner tr=spin(trucks);f.addView(label("Camión"));f.addView(tr);
  Spinner trail=spin(trailers);f.addView(label("Acoplado"));f.addView(trail);
  Spinner cont=spin(new String[]{"GDE 30 ROLL","MED 20 ROLL","CHICO 15 ROLL","GDE 18 PORTA","CHICO 8 PORTA"});f.addView(label("Contenedor"));f.addView(cont);
  Spinner dest=spin(destinations);f.addView(label("Destino / disposición"));f.addView(dest);
  Spinner st=spin(states);st.setSelection(1);f.addView(label("Estado"));f.addView(st);
  TextView mat=tx("Seleccionar materiales",13,GREEN);mat.setBackground(shape(PANEL2,12));final boolean[] sel=new boolean[materials.length];final String[] chosen={""};mat.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Materiales").setMultiChoiceItems(materials,sel,(a,i,on)->sel[i]=on).setPositiveButton("ACEPTAR",(a,b)->{StringBuilder z=new StringBuilder();for(int i=0;i<materials.length;i++)if(sel[i]){if(z.length()>0)z.append(", ");z.append(materials[i]);}chosen[0]=z.toString();mat.setText(chosen[0].length()==0?"Seleccionar materiales":chosen[0]);}).show());f.addView(label("Materiales"));f.addView(mat);EditText obs=new EditText(this);obs.setHint("Observaciones");f.addView(obs);
  int target=day<0?0:day;new AlertDialog.Builder(this).setTitle("Nuevo viaje · "+days[target]).setView(sc).setPositiveButton("GUARDAR",(x,y)->{int row=findCompany(co.getText().toString());String val=(tm.getText().length()>0?tm.getText()+" ":"")+ser.getSelectedItem().toString()+(chosen[0].length()>0?" · "+chosen[0]:"")+" · "+drv.getSelectedItem()+" · "+tr.getSelectedItem()+" · "+trail.getSelectedItem()+" · "+cont.getSelectedItem()+" · "+dest.getSelectedItem()+(obs.getText().length()>0?" · OBS: "+obs.getText():"")+" · "+st.getSelectedItem().toString();appendTrip(row,target,val);saveHistory("ALTA",companies[row]+" · "+days[target]+" · "+val);render();}).setNegativeButton("Cancelar",null).show();
 }
 TextView label(String s){TextView v=tx(s,11,MUTED);v.setTypeface(null,1);return v;}
 Spinner spin(String[] a){Spinner s=new Spinner(this);ArrayAdapter<String>x=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a);s.setAdapter(x);return s;}
 int findCompany(String s){return ensureCompany(s);}
 void tripMenu(int r,int d){String[] list=trips(r,d);if(list.length>1){String[] names=new String[list.length];for(int i=0;i<list.length;i++)names[i]=(i+1)+" · "+list[i];new AlertDialog.Builder(this).setTitle(companies[r]+" · "+days[d]+" · VIAJES").setItems(names,(a,i)->tripActions(r,d,i)).setNegativeButton("+ NUEVO VIAJE",(a,b)->form(companies[r],d)).show();return;}tripActions(r,d,0);}
 void tripActions(int r,int d,int idx){String[] list=trips(r,d);if(list.length==0)return;String v=list[idx];String[] a={"VER VIAJE","CAMBIAR ESTADO","EDITAR / REPROGRAMAR","DUPLICAR","FOTOS / EVIDENCIAS","VER EVIDENCIAS","GENERAR PDF","CANCELAR VIAJE"};new AlertDialog.Builder(this).setTitle(companies[r]+" · "+days[d]+"\n"+v).setItems(a,(x,w)->{if(w==0)new AlertDialog.Builder(this).setTitle("Ficha del viaje · "+companies[r]+" · "+days[d]).setMessage("SEMANA: "+weekTitle.getText()+"\n\n"+v+"\n\nToque CAMBIAR ESTADO para avanzar el viaje.\nMantenga pulsada una empresa para marcarla favorita.").setPositiveButton("Cerrar",null).show();if(w==1)stateDialog(r,d,idx,v);if(w==2)editTrip(r,d,idx,v);if(w==3){int nd=(d+1)%7;appendTrip(r,nd,v);saveHistory("DUPLICADO",companies[r]+" · "+days[d]+" → "+days[nd]);render();}if(w==4)photos(r,d,idx);if(w==5)makePdf(r,d,v);if(w==6){replaceTrip(r,d,idx,v.replace("PROGRAMADO","CANCELADO").replace("EN CURSO","CANCELADO").replace("PEDIDO PENDIENTE","CANCELADO"));saveHistory("CANCELADO",companies[r]+" · "+days[d]);render();}}).show();}
 void replaceTrip(int r,int d,int idx,String nv){String[] a=trips(r,d);if(idx<0||idx>=a.length)return;a[idx]=nv;StringBuilder z=new StringBuilder();for(int i=0;i<a.length;i++){if(i>0)z.append("||");z.append(a[i]);}db.edit().putString(key(r,d),z.toString()).apply();}
 void stateDialog(int r,int d,int idx,String v){new AlertDialog.Builder(this).setTitle("Cambiar estado").setItems(states,(x,i)->{String nv=v;for(String z:states)nv=nv.replace(z,states[i]);replaceTrip(r,d,idx,nv);saveHistory("ESTADO",companies[r]+" · "+states[i]);render();}).show();}
 void editTrip(int r,int d,int idx,String old){final EditText e=new EditText(this);e.setText(old);e.setMinLines(4);new AlertDialog.Builder(this).setTitle("Editar / reprogramar viaje").setView(e).setPositiveButton("GUARDAR",(a,b)->{String nv=e.getText().toString().trim();String[] all=trips(r,d);if(nv.length()==0)return;if(conflict(r,d,nv)){new AlertDialog.Builder(this).setTitle("Conflicto detectado").setMessage("La nueva asignación coincide con chofer o camión ocupado. No se guardó el cambio.").setPositiveButton("OK",null).show();return;}all[idx]=nv;db.edit().putString(key(r,d),android.text.TextUtils.join("||",all)).apply();saveHistory("EDITAR / REPROGRAMAR",companies[r]+" · "+days[d]+" · "+nv);render();}).setNegativeButton("Cancelar",null).show();}
 void moveTrip(int r,int oldDay,int idx,String v){new AlertDialog.Builder(this).setTitle("Mover viaje a otro día").setItems(days,(a,newDay)->{if(newDay==oldDay)return;String nv=v.replace("PROGRAMADO","REPROGRAMADO");if(conflict(r,newDay,nv)){new AlertDialog.Builder(this).setTitle("Conflicto detectado").setMessage("El chofer o camión ya está asignado en ese horario. El viaje permanece en su día original.").setPositiveButton("OK",null).show();return;}String[] old=trips(r,oldDay);if(idx<0||idx>=old.length)return;ArrayList<String> keep=new ArrayList<>();for(int i=0;i<old.length;i++)if(i!=idx)keep.add(old[i]);db.edit().putString(key(r,oldDay),android.text.TextUtils.join("||",keep)).apply();String oldEv=db.getString(evidenceKey(r,oldDay,idx),"");appendTrip(r,newDay,nv);if(oldEv.length()>0){String[] moved=trips(r,newDay);int ni=-1;for(int q=0;q<moved.length;q++)if(moved[q].equals(nv)){ni=q;break;}if(ni>=0)db.edit().putString(evidenceKey(r,newDay,ni),oldEv).apply();saveHistory("EVIDENCIA MIGRADA",companies[r]+" · "+days[newDay]);}saveHistory("MOVER / REPROGRAMAR",companies[r]+" · "+days[oldDay]+" → "+days[newDay]);render();}).show();}
 void detail(int r,int d,int idx,String v){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(28,18,28,18);TextView title=tx(companies[r],22,WHITE);title.setTypeface(null,1);box.addView(title);box.addView(tx(days[d]+" · "+weekTitle.getText(),14,GREEN));for(String part:v.split(" · "))box.addView(tx(part,15,WHITE));String raw=db.getString(evidenceKey(r,d,idx),db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,""));box.addView(tx("Evidencias: "+(raw.length()==0?0:raw.split("\\|\\|").length),14,MUTED));ScrollView sc=new ScrollView(this);sc.addView(box);new AlertDialog.Builder(this).setTitle("Ficha del viaje").setView(sc).setPositiveButton("Cerrar",null).show();}
 String evidenceKey(int r,int d,int idx){String[] a=trips(r,d);String v=(idx>=0&&idx<a.length)?a[idx]:"";return "evidence_"+wk()+"_"+r+"_"+d+"_"+Integer.toHexString(v.hashCode());}
 void openEvidence(int r,int d,int idx){String raw=db.getString("photo_"+wk()+"_"+r+"_"+d+"_"+idx,"");if(raw.length()==0){new AlertDialog.Builder(this).setTitle("Evidencias").setMessage("Este viaje todavía no tiene fotos adjuntas.").setPositiveButton("OK",null).show();return;}String[] us=raw.split("\\|\\|");String[] labels=new String[us.length];for(int i=0;i<us.length;i++)labels[i]="Evidencia "+(i+1);new AlertDialog.Builder(this).setTitle("Abrir evidencia").setItems(labels,(a,n)->{try{Intent it=new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(us[n]));it.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(it);}catch(Exception ex){new AlertDialog.Builder(this).setMessage("No se pudo abrir esta evidencia.").setPositiveButton("OK",null).show();}}).show();}
 void photos(int r,int d,int idx){String k="photo_"+wk()+"_"+r+"_"+d+"_"+idx;String raw=db.getString(k,"");int count=raw.length()==0?0:raw.split("\\|\\|").length;new AlertDialog.Builder(this).setTitle("Fotos / evidencias").setMessage("Evidencias vinculadas: "+count).setPositiveButton("+ AGREGAR",(a,b)->{photoRow=r;photoDay=d;photoIdx=idx;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,700);}).setNegativeButton("Cerrar",null).show();}
 void makePdf(int r,int d,String v){try{PdfDocument pdf=new PdfDocument();PdfDocument.Page page=pdf.startPage(new PdfDocument.PageInfo.Builder(595,842,1).create());Paint p=new Paint();p.setColor(Color.BLACK);p.setTextSize(26);p.setFakeBoldText(true);page.getCanvas().drawText("FAVORABLE · FICHA DE VIAJE",42,65,p);p.setFakeBoldText(false);p.setTextSize(15);int y=110;String[] ls={companies[r],weekTitle.getText().toString(),days[d],v};for(String line:ls){page.getCanvas().drawText(line,42,y,p);y+=34;}pdf.finishPage(page);File dir=new File(getExternalFilesDir(null),"pdf");dir.mkdirs();File out=new File(dir,"Viaje_"+System.currentTimeMillis()+".pdf");FileOutputStream os=new FileOutputStream(out);pdf.writeTo(os);os.close();pdf.close();saveHistory("PDF",out.getName());new AlertDialog.Builder(this).setTitle("PDF generado").setMessage(out.getAbsolutePath()).setPositiveButton("OK",null).show();}catch(Exception e){Toast.makeText(this,"No se pudo generar PDF",Toast.LENGTH_LONG).show();}}
 void backup(){try{File dir=new File(getExternalFilesDir(null),"backup");dir.mkdirs();File out=new File(dir,"FavorableViajes_"+new SimpleDateFormat("yyyyMMdd_HHmm",Locale.US).format(new Date())+".txt");FileOutputStream os=new FileOutputStream(out);StringBuilder z=new StringBuilder();for(Map.Entry<String,?> e:db.getAll().entrySet())z.append(e.getKey()).append("=").append(String.valueOf(e.getValue())).append("\n");os.write(z.toString().getBytes("UTF-8"));os.close();saveHistory("BACKUP",out.getName());new AlertDialog.Builder(this).setTitle("Backup creado").setMessage(out.getAbsolutePath()).setPositiveButton("OK",null).show();}catch(Exception e){Toast.makeText(this,"Error de backup",Toast.LENGTH_LONG).show();}}
 void restoreLatest(){try{File dir=new File(getExternalFilesDir(null),"backup");File[] fs=dir.listFiles();if(fs==null||fs.length==0){Toast.makeText(this,"No hay backups",Toast.LENGTH_SHORT).show();return;}Arrays.sort(fs,(a,b)->Long.compare(b.lastModified(),a.lastModified()));BufferedReader br=new BufferedReader(new InputStreamReader(new FileInputStream(fs[0]),"UTF-8"));SharedPreferences.Editor ed=db.edit().clear();String line;while((line=br.readLine())!=null){int p=line.indexOf('=');if(p>0){String k=line.substring(0,p),v=line.substring(p+1);if(k.startsWith("fav_"))ed.putBoolean(k,Boolean.parseBoolean(v));else ed.putString(k,v);}}br.close();ed.apply();saveHistory("RESTAURADO",fs[0].getName());render();Toast.makeText(this,"Backup restaurado",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"No se pudo restaurar",Toast.LENGTH_LONG).show();}}
 void history(){String h=db.getString("history","Sin movimientos todavía.");ScrollView sc=new ScrollView(this);TextView v=tx(h,13,WHITE);v.setBackgroundColor(BG);sc.addView(v);new AlertDialog.Builder(this).setTitle("Historial / trazabilidad").setView(sc).setPositiveButton("Cerrar",null).show();}
 void toolsMenu(){String[] x={"RESTAURAR ÚLTIMO BACKUP","RESUMEN POR EMPRESA","HISTORIAL"};new AlertDialog.Builder(this).setTitle("Herramientas").setItems(x,(a,n)->{if(n==0)restoreLatest();if(n==1)companySummary();if(n==2)history();}).setNegativeButton("Cerrar",null).show();}
 void companySummary(){StringBuilder z=new StringBuilder("SEMANA "+wk()+"\nRESUMEN POR EMPRESA\n\n");for(int r=0;r<companies.length;r++){int n=0;for(int d=0;d<7;d++)n+=trips(r,d).length;if(n>0)z.append(companies[r]).append("  ·  ").append(n).append(" viaje(s)\n");}new AlertDialog.Builder(this).setTitle("Resumen semanal por empresa").setMessage(z.toString()).setPositiveButton("Cerrar",null).show();}
 void stats(){int total=0,rea=0,prog=0,curso=0,repro=0,canc=0,ped=0;for(int r=0;r<companies.length;r++)for(int d=0;d<7;d++)for(String v:trips(r,d)){total++;if(v.contains("REALIZADO"))rea++;else if(v.contains("EN CURSO"))curso++;else if(v.contains("REPROGRAMADO"))repro++;else if(v.contains("CANCELADO"))canc++;else if(v.contains("PEDIDO PENDIENTE"))ped++;else prog++;}String m="TOTAL  "+total+"\n\nREALIZADOS  "+rea+"\nEN CURSO  "+curso+"\nPROGRAMADOS  "+prog+"\nPEDIDOS PENDIENTES  "+ped+"\nREPROGRAMADOS  "+repro+"\nCANCELADOS  "+canc;new AlertDialog.Builder(this).setTitle("Estadísticas · "+weekTitle.getText()).setMessage(m).setPositiveButton("Cerrar",null).show();}
}
